### ISSUE TITLE
How to set initial value to every field?

### ISSUE THREAD

**Issue by chiga0** [react-querybuilder/react-querybuilder#106]
I want to set the initial value for each field. How do I set it up?
![image](https://user-images.githubusercontent.com/24784430/65303715-54358a00-dbb1-11e9-852e-acba3e34c7d1.png)

Like the DatePicker component above, setting the initial value is very necessary.

**Comment by jakeboone02** [comment]
You'll need to use a custom `ValueEditor` component.  You can hard-code the default value in the custom component or get it from the `fieldData` prop (if you're using >=2.4.0).

Something like this:

```js
const ValueEditor = ({field, fieldData}) =>
  <input defaultValue={fieldData.defaultValue} /*...*/ />;

const QueryComponent = () => (
  <QueryBuilder
   fields={[{name: 'field1', label: 'Field 1', defaultValue: 'Default Value'}]}
   controlElements={{valueEditor: ValueEditor}}
   /*...*/
  />;
);
```

**Comment by AbelRodriguezGumiel** [comment]
It is not possible to set the initial value, even if you use a custom component, the value in the query is not set until the onChange event fires, so even if you set an initial value in the custom component, this is not seen in the generated query.

This forces the user to change the value, and change it again so that the value is set.

For example in a checkbox, if the initial value is "false", the initial value in the query is empty. To put "false" you must check the checkbox and then uncheck it so that in the query it says "false".

The initial value should be reflected in the query to avoid this.

**Comment by jakeboone02** [comment]
@AbelRodriguezGumiel Could you use a `useEffect` hook to fire the `handleOnChange` function when the custom `ValueEditor` mounts?  Like this:

```js
const ValueEditor = ({field, fieldData, handleOnChange, value}) => {
  useEffect(() => {
    handleOnChange(fieldData.defaultValue);
  }, []);

  return <input value={value} onChange={e => handleOnChange(e.target.value)} /*...*/ />;
}

const QueryComponent = () => (
  <QueryBuilder
   fields={[{name: 'field1', label: 'Field 1', defaultValue: 'Default Value'}]}
   controlElements={{valueEditor: ValueEditor}}
   /*...*/
  />;
);
```

**Comment by AbelRodriguezGumiel** [comment]
Yes I could. Thanks for the reply
