### ISSUE TITLE
New Feature to provide Action for set of Rules

### ISSUE THREAD

**Issue by jitendra9nov** [react-querybuilder/react-querybuilder#108]
Is it possible to provide some action field for set of rules and provide that action in the Json Query?

**Comment by jakeboone02** [comment]
I'm not sure I understand your question.  Could you provide a code sample or elaborate on your use case?

**Comment by jitendra9nov** [comment]
Thank you for your kind response.

Unfortunately I don't have code sample with me. I will try to explain my problem statement.

I am developing a feature to provide some Actions on the basis of configured Rules. So I am using react-qurybuilder here. With this I am able to provide option to configure rule but unable to attach action to it on the same page. I also want that actin to reflect in generated Query (json format)

**Example:**
RuleSet1 ---> Action 1
RuleSet2 ---> Action 2

**Final Query:** 
```json
{
  "ruleset": {
    "combinator": "and",
    "not": false,
    "rules": [
      {
        "field": "firstName",
        "operator": "null",
        "value": ""
      },
      {
        "field": "lastName",
        "operator": "null",
        "value": ""
      },
      {
        "combinator": "and",
        "rules": [
          {
            "field": "age",
            "operator": ">",
            "value": "30"
          }
        ]
      }
    ]
  },
  "action": "Action Object or String"
}
```

**Comment by systemsarchitecture** [comment]
hi, i need this feature,  its rule builder, is it possible with react-queyBuilder ?

**Comment by jakeboone02** [comment]
Hi, @systemsarchitecture. Almost three years later, I think I know now what @jitendra9nov was getting at, and probably what you're looking for as well: a [rules engine](https://martinfowler.com/bliki/RulesEngine.html) -- basically a series of if-then statements.

`react-querybuilder` is designed to construct the "if" part, but not the "if" and "then" parts together. If the "then" actions follow the same field-operator-value pattern, then I guess you could have two query builders for each if-then statement: one to build the "if" conditions and one to design the "then" actions.

I used the "insurance premium" example from [this article](https://martinfowler.com/bliki/RulesEngine.html) to sketch out the basic technique in [this codesandbox](https://codesandbox.io/s/w4m2ox?file=/src/App.tsx). Let me know if that helps!

**Comment by jakeboone02** [comment]
I have some new thoughts on this topic. Please see https://github.com/react-querybuilder/react-querybuilder/issues/919#issuecomment-3146746032.

**Comment by jakeboone02** [comment]
OK I've finally produced something of substance regarding this request.

What I came up with was a companion package `@react-querybuilder/rules-engine` which builds on `react-querybuilder` with a `RulesEngineBuilder` component. It also includes the method `formatRulesEngine`&mdash;an export function like `formatQuery`&mdash;currently supporting [`json-rules-engine`](https://github.com/CacheControl/json-rules-engine).

I'm going to leave this package purposely undocumented (or maybe _lightly_ documented) for now to allow for feedback-directed changes and improvements without having to rewrite docs.

You can install the package from npm:

```sh
npm i @react-querybuilder/rules-engine
# OR yarn add / pnpm add / bun add
```

I've also set up a sandbox here: https://stackblitz.com/edit/github-hahtpo1r?file=src%2FApp.tsx

The data structure ended up being more of a wrapper around RQB's standard query object rather than an augmentation of it. Each step in an if-else chain identifies an `antecedent` (the "if" or "else if" condition) and an optional `consequent` (the result or action to be taken when a condition is true).

A rules engine object might look like this: 

```ts
const re: RulesEngine = {
  // Series of conditions ("if, else-if, else-if, ...")
  conditions: [
    // Condition 1 ("if...")
    {
      // Antecedents are query builder objects (`RuleGroupType`/`RuleGroupTypeIC`)
      antecedent: {
        combinator: "and",
        rules: [{ field: "age", operator: ">=", value: 18 }],
      },

      // Consequents ("then...") are the result of a successful/passing antecedent
      // They can be any object with a `type` property
      consequent: {
        type: "send_email",
        params: { to: "user@example.com", subject: "Welcome!", body: "Thanks for signing up!" },
      },

      // A condition can have sub-conditions
      conditions: [
        {
          antecedent: {
            combinator: "and",
            rules: [{ field: "age", operator: "=", value: 18 }],
          },
          consequent: {
            type: "send_email",
            params: { to: "user@example.com", subject: "Happy Birthday!", body: "🎂" },
          },
        },
      ],
    },

    // Condition 2 ("else if...")
    {
      antecedent: { combinator: "and", rules: [{ field: "age", operator: "<", value: 18 }] },

      // Consequent 2 ("then...")
      consequent: {
        type: "send_email",
        params: { to: "user@example.com", subject: "Sorry!", body: "Must be 18 to sign up." },
      },
    },
  ],

  // Optional "else" block
  defaultConsequent: { id: "3", type: "log_event" },
};
```

The prop types for the `RulesEngineBuilder` component are here:

https://github.com/react-querybuilder/react-querybuilder/blob/639867e705f4d23a85d06d5d15af540946d580e6/packages/rules-engine/src/types/props.ts#L129-L167

Please use #919 to ask any questions or add any feedback you may have.
