### ISSUE TITLE
Customize Select element.

### ISSUE THREAD

**Issue by UgurKacak** [react-querybuilder/react-querybuilder#129]
I need to customize select option list on rule part. Which I need to is like create a select box with option-groups and live search on selectlist. <select> can't get enought flexibility. So I need to use some custom select components. How I change this. Can you give an examle to use another component like I want in action. 
Thanx.

**Comment by jakeboone02** [comment]
The only way to customize the `ValueEditor` component is to pass in a custom component.  Here is an example with a `<select>` element.  Obviously you can do a lot more with it, but this shows the basics:

```js
import React from 'react';

const ValueEditor = ({ handleOnChange, value }) => (
  <select onChange={(e) => handleOnChange(e.target.value)} value={value}>
    <option value="test1">Test 1</option>
    <option value="test2">Test 2</option>
    <option value="test3">Test 3</option>
    <option value="test4">Test 4</option>
  </select>
);

const App = () => (
  <QueryBuilder
    fields={[{ name: "test", label: "Test" }]}
    controlElements={{ valueEditor: ValueEditor }}
    operators={[{ name: "=", label: "is" }]}
  />
);

//...
```

If you want to get really fancy you can use something like [`react-select`](https://react-select.com/).  Same principles apply, just use the `<Select>` component from `react-select` instead of the native `<select>` element.

**Comment by MohammedAlasaad** [comment]
Hi @jakeboone02 
It it possible to use react-select for fields and operators too ? instead of default select.

**Comment by jakeboone02** [comment]
@Mohammedalasaad - yes it is.  Just set the `controlElements.fieldSelector` and `controlElements.operatorSelector` options in your `<QueryBuilder>` props to a custom component.
