### ISSUE TITLE
Input Tag loses focus when using a custom onQueryChange handler

### ISSUE THREAD

**Issue by akhi9** [react-querybuilder/react-querybuilder#137]
### Version
3.1.2
### Problem
I have a parent component with  child component as the querybuilder component. I am setting the generated query in parent component's state using callback from and passing the updated query in props to the querybuilder component. But, everytime I enter one character in a input tag (of valueSelector control component in querybuilder) with a second input tag with empty value, the first input tag **loses focus**. 

Added the code at [stackblitz](https://stackblitz.com/edit/react-nqbl1c?file=Filter.js). 
Could you please help me fix this?

Thanks

**Comment by jakeboone02** [comment]
`ref` is being assigned to the `<input>`s as they're rendered, so it gets assigned to the first one, then the second one, during a render of the component.  Each time you type a character, the component re-renders.  Then your `useEffect` side effect runs to set focus on the ref'd element (which is the second one, even though you're typing in the first one).

I think what you're trying to do is set focus on the `<input>` when there is a _new_ rule, but your side effect is setting focus on the _last_ `<input>` after each render.  If that's correct, I honestly don't know how to accomplish what you want to do.  Using a `ref` in your `valueEditor` component is probably not the right idea because there could be multiple rules and therefore multiple instances of that component.

In any case, it doesn't look like an issue with `react-querybuilder`.

**Comment by akhi9** [comment]
Thank you for the explanation @jakeboone02 
I am sorry I have been trying to make this work, so may have accidentally updated the stackblitz. You are right using ref won't work. 
But, even without `useEffect` side effect each time I type a character `input` tag is losing focus. Updated the [stackblitz](https://stackblitz.com/edit/react-yy8q6n?file=Filter.js).

I wonder if I am not handling the `onQueryChange` handler correctly  for passing  `query` as prop to `react-querybuilder`.
   

```
this.setState({
      query,
      queryOutput: formatQuery(query, "sql")
    });
```

**Comment by jakeboone02** [comment]
I figured it out.  Your `valueEditor` component is defined inline with the `<QueryBuilder>` props, so it creates a new instance on each render.  You need to define the `valueEditor` component outside the JSX and just reference it.  I forked your stackblitz [here](https://stackblitz.com/edit/react-3so1vt?file=Filter.js) to show the fix.

**Comment by akhi9** [comment]
Cannot believe I missed that. Thanks a lot @jakeboone02.
