### ISSUE TITLE
formatQuery doesn't escape spaces in fields.

### ISSUE THREAD

**Issue by geo-systems** [react-querybuilder/react-querybuilder#154]
Hi,

I'm using `formatQuery(queryDefinition, "sql")` to generate SQL. 

I noticed that when a column name contains a space, the SQL value doesn't escape it. For example, when I have a filed/column `Item Type`, the resulting SQL is: `(Item Type is null)`.

I would like to escape the name of the column/fields so that the resulting SQL is escaped:

<pre>
(`Item Type` is null)
</pre>

I couldn't see an option in the documentation to do so.

**Comment by jakeboone02** [comment]
OK, so the question now is whether to _always_ quote the field names, or quote only the field names that contain spaces.  Also, should the delimiter always be a backtick?  I know Oracle uses double quotes.  Maybe that should be an option.

**Comment by jakeboone02** [comment]
I've had an idea to reconfigure the `formatQuery` parameters for a while now, and this ticket makes me think it's time to do it.  The change will be:  an options object can be passed instead of the format string.  So instead of `formatQuery(query, 'sql')` you can do `formatQuery(query, { format: 'sql' })`.  Other options will be `valueProcessor` (formerly the optional third parameter) and `quoteFieldNamesWith`, which can be, for example, ``"`"`` to quote field names with backticks.  I'll put a PR together that you can take a look at before I publish.
