### ISSUE TITLE
Switch to changelog-cli for changelog generation

### ISSUE THREAD

**Issue by pavanpodila** [react-querybuilder/react-querybuilder#16]
@maniax89 The current approach to changelog generation relies on a ruby toolset. Let's switch to an NPM based approach with `changelog-cli`: https://github.com/conventional-changelog/conventional-changelog-cli 

With that we can create a npm script and get things done more easily. Also the above is used by big projects like angular, karma-runner, etc.

Also I've pushed the tags, so we should have every tag from the beginning, including the **1.3.0**

**Comment by maniax89** [comment]
I liked using the github-based one because it pulls in the issues/PRs/tags/etc. from the github repo as opposed to relying on specific commit formats. I understand it requires ruby toolset instead of npm so I can search for one that is npm-based, but the one you referenced won't give much benefit unless the commits follow an opinionated format.

**Comment by pavanpodila** [comment]
It would be great to be in the npm ecosystem. Hopefully there is a solution

Thanks,
Pavan

**Comment by pavanpodila** [comment]
Lets go with the ruby approach for now and make the 1.3 release. Lets make the new changelog based on the tag I pushed. Once you are done, I can do a npm release!

**Comment by maniax89** [comment]
See #17
