### ISSUE TITLE
Query builder validation support in Value Editor.

### ISSUE THREAD

**Issue by sonalyadav8924** [react-querybuilder/react-querybuilder#166]
I was looking to add some validation logic and highlighting in the Errors near each Value editor of Query builder.
I couldn't find anything in documentation.
Can we add support for form validation in QueryBuilder, which will trigger a validation call to all the ValueEditors.

**Comment by jakeboone02** [comment]
Could you describe how you would expect the API to work?  I'm not exactly sure how to pull that off in a way that would necessarily be acceptable to the community.

**Comment by sonalyadav8924** [comment]
i want errors to be displayed below Value editor of Query builder. I have attached example for reference.
<img width="847" alt="Screenshot 2020-12-03 at 6 03 54 PM" src="https://user-images.githubusercontent.com/63401251/101019150-8bb00c80-3592-11eb-8cc2-e14725f17740.png">

**Comment by jakeboone02** [comment]
I think the best option here is to use a custom ValueEditor component with its own validation logic -- unless you can think of a truly generic way to implement query validation. Trying to think about it myself, I've come up with a couple of options (e.g. adding `valid` or `invalid` classes to the value editor based on the result of a provided validation function), but nothing that beats a custom ValueEditor.

**Comment by jakeboone02** [comment]
Just to update everyone, I'm still thinking about this. Another user requested a similar feature in #213. Right now what's going through my head is the possibility of adding a default validation function for rules, with the option to override that function with a custom function. Still not sure how that would affect the `<QueryBuilder>` output exactly.

**Comment by vijayky** [comment]
Thinking if Field prop should receive a callback function, which accepts all props as ValueEditor props and returns an object (as below) to indicate validation status. 

**Possible return value from validation function**
```javascript
{
   isValid: boolean,
   reasons: [string, ...]
}
```

The validation function may be called on blue of value editor and formatQuery aka query structure is built.

**Comment by jakeboone02** [comment]
I've been thinking about this a little bit more (thanks to @vijayky for the prod!) and wanted to run my idea by the community before I implemented anything. I was thinking we could accept a `validate` prop which `QueryBuilder` would invoke on each render.

The result of that function would need to be a `boolean` indicating whether the entire query is valid, or an object where the keys are the `id`s of groups and rules within the query. The value associated with each key in the object would either be a `boolean` indicating whether that rule/group is valid, or an object with the following shape: `{ valid: boolean; reasons: any[]; }` (again, thanks @vijayky). The object version would indicate validity with the `valid` key, and provide a list of `reasons` in some form (presumably `string`s, but I thought it would be good to be flexible in case someone wanted to go crazy with it) usable by, for example, a custom `ValueEditor`.

This is how the new prop would be defined in the main props interface:

```ts
interface QueryBuilderProps {
  // ...
  validate?(
    query: RuleGroupType
  ): boolean | { [id: string]: boolean | { valid: boolean; reasons: any[] } };
  // ...
}
```

## Examples

Consider the following query:

```json
{
  "id": "g-rootGroup",
  "combinator": "and",
  "rules": [
    {
      "id": "r-firstRule",
      "field": "firstName",
      "operator": "=",
      "value": "Jake"
    },
    {
      "id": "g-childGroup",
      "combinator": "and",
      "rules": []
    }
  ]
}
```

Let's first assume the `validate` function returns a `boolean`. If `validate(query) === true`, then the HTML output would be something like this:

```html
<div class="queryBuilder queryBuilder-valid">
  <!-- ...rest of query HTML is like normal (no extra classes) -->
</div>
```

If `validate(query) === false`:

```html
<div class="queryBuilder queryBuilder-invalid">
  <!-- ...rest of query HTML is like normal (no extra classes) -->
</div>
```

Now let's assume `validate(query)` returned an object that looked like this:

```ts
{
  "g-rootGroup": { valid: false, reasons: ['A sub-group is invalid'] },
  "r-firstRule": true,
  "g-childGroup": { valid: false, reasons: ['Empty rules array']},
}
```

The HTML output would be something like this:

```html
<div class="queryBuilder">
  <div class="ruleGroup queryBuilder-invalid">
    <!-- ^ invalid due to invalid child group -->
    <div class="ruleGroup-header"><!-- ... --></div>
    <div class="rule queryBuilder-valid">
      <!-- ^ valid since `!!rule.value === true` -->
      <!-- ...rest of the rule HTML is like normal -->
    </div>
    <div class="ruleGroup queryBuilder-invalid">
      <!-- ^ invalid due to empty `rules` array -->
      <div class="ruleGroup-header"><!-- ... --></div>
    </div>
  </div>
</div>
```

## Implementation details for anyone that cares

<details>
  <summary>Click to show</summary>

This is roughly how the QueryBuilder component would implement the new prop:

```ts
// TODO: extract all standard classes into constants
const standardClassValid = 'queryBuilder-valid';
const standardClassInvalid = 'queryBuilder-invalid';

// in QueryBuilder.tsx:
if (typeof validate === 'function') {
  const validationResult = validate(root);

  if (typeof validationResult === 'boolean') {
    const classToAdd = validationResult ? standardClassValid : standardClassInvalid;
    // add `classToAdd` to root `QueryBuilder` component
  } else {
    if (validationResult[rootId]) {
      // apply class to root component based on `validationResult[rootId].valid`, (same as above)
    }
    // and pass down the `validationResult` object to child groups/rules
  }
}
```

And then in each child group/rule:

```ts
if (typeof validationResult[id] === 'boolean') {
  const classToAdd = validationResult[id] ? standardClassValid : standardClassInvalid;
  // add classToAdd to this component
} else {
  const classToAdd = validationResult[id].valid ? standardClassValid : standardClassInvalid;
  // add classToAdd to this component, and
  // pass `validationResult[id]` down to each child component,
  // i.e. CombinatorSelector, FieldSelector, ValueEditor, etc.,
  // so they can display the `results` messages on the screen (or whatever)
}
```

</details>

What does everyone think?

**Comment by vijayky** [comment]
Thanks @jakeboone02  for providing awesome notes, this is how I am reflecting after reviewing above:

There could be three levels of validation
* Field level
  * Field level validation may trigger after value change on ValueEditor. 
  * The validation logic can be provided with Field prop so that not all validation checks would occur each time. 
  * The another benefit would be that field validation logic is separated and single `validate` function would not become a hub of all validation. 
  * I also see a benefit when only certain fields are loaded in the query builder, in that case the `validate` function would not have validation logic for the fields not loaded.
  * Users don't have to deal with `id`s return returning validation result.
* Group level
  * I could only think of two validations for any group
    * The combinator has value
    * The group has at least one rule
  * For those rules, may be implemented within QueryBuilder and available as out-of-the-box. Only user has to enable the validation rule
* Query level 
  * The query builder may trigger validation check on-demand and before `formatQuery`. I could iterate internally for each group added validation and if passes for each rule validation and combine validation status.
  * The validation summary could also be available to the user when validation is called on-demand. This way user may have change to show validation summary out of the QueryBuilder interface. Instead of looking each rule, it may help users to see validation summary at one place. 
  * The validation summary may contain rule / group field name and/or `id`s.

Validation callback could be `onValidate` on Field prop. The `validate` method could be created for on-demand calls. 

The HTML display looks good to me.

Thanks a lot Jake!

**Comment by jakeboone02** [comment]
Great comments. Thanks!

> - Field level
>   - Field level validation may trigger after value change on ValueEditor.
>   - The validation logic can be provided with Field prop so that not all validation checks would occur each time.
>   - The another benefit would be that field validation logic is separated and single `validate` function would not become a hub of all validation.
>   - I also see a benefit when only certain fields are loaded in the query builder, in that case the `validate` function would not have validation logic for the fields not loaded.
>   - Users don't have to deal with `id`s return returning validation result.

I do like the idea of `Field`-based validation callbacks. I think they should be invoked on each render, at the `Rule` level, and the results passed down to each sub-component (including `ValueEditor`). The function signature would be something like `validate?(params: RuleProps): boolean | {/* same object as query-level */}`.

Similar to `Field`-specific validators, we could have a `ruleValidator` prop. Function signature would be the same as the `Field` validator in the last paragraph, but it would be one function to handle all `Rule`s. Well, maybe that's overkill and you could just assign the same validation function to all Fields to achieve the same effect. Hmmm.

> - Group level
>   - I could only think of two validations for any group
>     - The combinator has value
>     - The group has at least one rule
>   - For those rules, may be implemented within QueryBuilder and available as out-of-the-box. Only user has to enable the validation rule

What about a `boolean` prop called `invalidateEmptyGroups` which, if `true`, would add the `"queryBuilder-invalid"` class to each empty group?

> - Query level
>   - The query builder may trigger validation check on-demand and before `formatQuery`. I could iterate internally for each group added validation and if passes for each rule validation and combine validation status.
>   - The validation summary could also be available to the user when validation is called on-demand. This way user may have change to show validation summary out of the QueryBuilder interface. Instead of looking each rule, it may help users to see validation summary at one place.
>   - The validation summary may contain rule / group field name and/or `id`s.
>
> Validation callback could be `onValidate` on Field prop. The `validate` method could be created for on-demand calls.

Not sure what you mean by "on-demand calls." Those don't need to be made by `QueryBuilder`. You can do those outside of the `QueryBuilder` component definition, based on the `onQueryChange` callback.

It seems like you're thinking the validation object is something `QueryBuilder` will provide to the user, but it's the other way around. The user provides the function to `QueryBuilder`, and the output of that function is passed on during the render phase to all sub-components to use as they wish. If you need a validation result outside of the `QueryBuilder` component tree, you can already do that whenever you like, however you like. The purpose of this issue is to facilitate changes internal to the library's JSX output.

**Comment by vijayky** [comment]
Impressed with you efforts...


> I do like the idea of Field-based validation callbacks. I think they should be invoked on each render, at the Rule level, and the results passed down to each sub-component (including ValueEditor). The function signature would be something like validate? (params: RuleProps): boolean | {/* same object as query-level */}.

👍 


> Similar to Field-specific validators, we could have a ruleValidator prop. Function signature would be the same as the Field validator in the last paragraph, but it would be one function to handle all Rules. Well, maybe that's overkill and you could just assign the same validation function to all Fields to achieve the same effect. Hmmm.

Yes, you are right, we don't need at Rule level



> What about a boolean prop called invalidateEmptyGroups which, if true, would add the "queryBuilder-invalid" class to each empty group?

👍, and, I mentioned a another validation for missing combinator value by thinking that user may override combinator in `combinatorSelector` may miss setting values. So having an inbuild validation for missing combinator value when 2 or more rules exist in a group.



> Not sure what you mean by "on-demand calls." Those don't need to be made by QueryBuilder. You can do those outside of the QueryBuilder component definition, based on the onQueryChange callback.

I was thinking on-demand calls like, user has `query` object and if there is a function that accepts `query` object and performs validations on entire tree. _(ex: `formatQuery` call, that take a `query` object and returns SQL, same way return validation result.)_ Since fields with validators are already provided. Query Builder knows about query expression tree so it can use `query` object and call each validation functions (including group validation) and return combined validation result. This way novice developers don't have to do heavy lifting. 

Thank you...

**Comment by jakeboone02** [comment]
Thanks for the quick feedback.

> > What about a boolean prop called `invalidateEmptyGroups` which, if true, would add the `"queryBuilder-invalid"` class to each empty group?
> 
> 👍, and, I mentioned a another validation for missing combinator value by thinking that user may override combinator in `combinatorSelector` may miss setting values. So having an inbuild validation for missing combinator value when 2 or more rules exist in a group.

OK, new prop will be `validateGroups?: boolean` (default `false`). When `true`, then empty groups and groups with 1) an invalid/missing combinator, and 2) `rules.length >= 2`, get invalidated. I.e., `"queryBuilder-invalid"` class on the group `div` and something like `{ valid: false, reasons: ['empty', 'invalid combinator'] }` passed to each sub-component.

> I was thinking on-demand calls like, user has `query` object and if there is a function that accepts `query` object and performs validations on entire tree. _(ex: `formatQuery` call, that take a `query` object and returns SQL, same way return validation result.)_ Since fields with validators are already provided. Query Builder knows about query expression tree so it can use `query` object and call each validation functions (including group validation) and return combined validation result. This way novice developers don't have to do heavy lifting.

Alright, I think I see what you mean now. This library can export a default validation function (like it does for `formatQuery`), which does the heavy lifting of, for example, recursively looping through the query tree and validating each rule/group. It would use this function internally as well, unless the user provided their own. Is that what you were thinking?

**Comment by vijayky** [comment]
Yes, this looks amazing, thanks Jake

**Comment by jakeboone02** [comment]
I've opened PR #225 to add the validation features discussed here. One change: I abandoned the `validateGroups` prop as it was redundant -- you can achieve the same effect by passing the exported `defaultValidator` as the `validator` prop.

**Comment by jakeboone02** [comment]
Validation features are included in [v3.12.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v3.12.0).

**Comment by balboFK** [comment]
Hey @jakeboone02 !
With this new feature, is possible to validate aswell the rules generated by JSON output? I'm trying to implement a validator which doesnt allow empty rules and empty groups, the CSS for the fields works just fine using the default validator, but i'm wondering a way of having "formatQuery" to tell me if some of the rules are invalid, so i would take some action after the check.

Thanks for the new feature, btw.

**Comment by jakeboone02** [comment]
If all you want to do is invalidate empty groups and rules (by which I assume you mean rules with falsy values), then you can use the code I provided in #226, modified to add a `valid` boolean property to each rule and group:

```ts
import { RuleGroupType, RuleType } from 'react-querybuilder';

const fields = [
  { name: 'description', label: 'Description', inputType: 'string' },
  { name: 'price', label: 'Price', inputType: 'number' }
];

const processRule = (r: RuleType): RuleType & { inputType?: string; valid?: boolean; } => ({
  ...r,
  valid: !!r.value, // invalidate rules with falsy values
  inputType: fields.find((f) => f.name === r.field)?.inputType
});

const processGroup = (rg: RuleGroupType): RuleGroupType & { valid?: boolean } => ({
  ...rg,
  valid: rg.rules.length > 0, // invalidate empty groups
  rules: rg.rules.map((r: RuleType | RuleGroupType) => {
    if (r['field' as 'id']) {
      return processRule(r as RuleType);
    }
    return processGroup(r as RuleGroupType);
  })
});

const result = processGroup(query);
```

**Comment by balboFK** [comment]
With that i can iterate over the object and cancel the following actions if any of the validations are false. 
I'll try to do that! 

Thanks again @jakeboone02 !
