### ISSUE TITLE
How to compare 2 fields, instead of a field and a specific value?

### ISSUE THREAD

**Issue by enzoampil** [react-querybuilder/react-querybuilder#192]
My use case requires 2 fields to be compared, instead of 1 field being compared to a single value. 

E.g.

`var1 > var2 AND var3 <> var4`

Is there a way to do this currently?

**Comment by jakeboone02** [comment]
There is a way to do this, with a custom `ValueEditor` and (if you're using `formatQuery` to generate your SQL) a custom `valueProcessor`.  See [this codesandbox](https://codesandbox.io/s/condescending-poincare-sw8tr?file=/src/App.tsx).  After you add a rule, check the box to the right of the value editor to convert it to using fields instead of values.

### Update 2022-02-01:

As of [v4.2.0](/react-querybuilder/react-querybuilder/releases/tag/v4.2.0), `react-querybuilder` has official support for field-to-field comparisons without using a custom `ValueEditor` ([documentation](https://react-querybuilder.js.org/docs/api/valueeditor#value-sources)).

**Comment by enzoampil** [comment]
got it thanks!

**Comment by jakeboone02** [comment]
@enzoampil in case you're still interested, please see the update to my comment above.
