### ISSUE TITLE
Apply 'getEditor' logic of producing a React component to other elements

### ISSUE THREAD

**Issue by maniax89** [react-querybuilder/react-querybuilder#2]
Thinking about using this plugin in a project I am working on and it would be really nice if the same logic implemented by the `getEditor` was applied across the other components as well in order to make it more customizable.

The 3 I have in mind right now are:
- [x] field selector
- [x] operator selector (almost there with the `getOperators`)
- [x] rule removal button

I would be potentially willing to contribute by making a fork/PR if needed

**Comment by pavanpodila** [comment]
That sounds good. I am assuming that you are trying to introduce more conditional control to decide the list of fields/operators/editors/actions on the fly. I think we can call that out with a configuration object instead of passing multiple props into the QueryBuilder.

How about a configurator that can do the following:

``` js
const configurator = {
  getEditor(field, operator){}, // Gives <SomeEditor />
  getFields(){}, // array of fields
  getActions(ruleOrGroup){} // array of valid actions (edit, delete)
};
```

The above might not be an exhaustive set, but hopefully gives you a sense of where I am going. 

Of course, would love a PR 😃

**Comment by maniax89** [comment]
Yeah the configuration object sounds fine. I was more interested in using the semantic ui react components in place of native browser elements http://semantic-ui.com/introduction/integrations.html
So I would probably have to take a closer look to see if it would be easy to implement as long as it makes the appropriate callback to your components
