### ISSUE TITLE
Can we add a new 'between' type? 

### ISSUE THREAD

**Issue by laportabellita** [react-querybuilder/react-querybuilder#201]
![Screen Shot 2021-05-31 at 11 37 07 AM](https://user-images.githubusercontent.com/82290980/120226696-11e59c80-c21e-11eb-9aa3-12b546abe690.png)
The screenshot shows a previous implementation that serves as an example of what we want to do with this library. We basically want to add a between function to it. 
We know that there's a couple of previous requests for this function and we would like to implement it ourselves  and share it with the community: 
https://github.com/react-querybuilder/react-querybuilder/pull/96
https://github.com/react-querybuilder/react-querybuilder/issues/73

We would use html’s native date input, but the difference is that between would, under the hood, there would be two inputs.
We want to add a case to the switch statement in ValueEditor.tsx. Does this sound ok? Before we start working on this, we want to make sure that we're implementing things in a way that you'll be ok with

**Comment by jakeboone02** [comment]
Hi @laportabellita, sorry it took me so long to get to this request.  In general I think this would be a good enhancement, and the `ValueEditor.tsx` modifications would be fairly straightforward, but you would probably need to modify the structure of the internal JSON representation of the query to accommodate two separate values.  That would be the bulk of the work -- making sure all the various TypeScript code conformed to the new format.  I might even make it a major version bump because of the new structure.  Just thinking out loud.  Go ahead and start your work and if you have any questions just reach out to me.  Thanks for being willing to contribute!

**Comment by MohammedAlasaad** [comment]
Anything new about this feature ? is it possible to implement it? Thanks

**Comment by jakeboone02** [comment]
I had an epiphany and realized this can be accomplished with the current feature set.  See [this codesandbox](https://codesandbox.io/s/angry-bardeen-c5tv0) for a simple example.

The key was to use an array of two elements instead of a primitive for `value` and handle it appropriately in a custom `ValueEditor`. I then passed a custom `valueProcessor` to the `formatQuery` function to produce the correct SQL. Voilà!

![image](https://user-images.githubusercontent.com/366438/129269617-37fa30f7-d41f-46dd-9c89-8d3a3879ec1d.png)

**Comment by jakeboone02** [comment]
Update:  [this codesandbox](https://codesandbox.io/s/jolly-leftpad-m1m9x) uses `react-datepicker` to [select a proper date range](https://reactdatepicker.com/#example-date-range-for-one-datepicker)! :)

![image](https://user-images.githubusercontent.com/366438/129276365-b2aeb9e5-5f13-4eef-bf9a-e84a9ae361d0.png)

**Comment by nageshwari17** [comment]
Hi @jakeboone02 , I think the above expample is working based on field . But its should work based on operator [this example](https://codesandbox.io/s/cool-rain-rem57?file=/src/App.tsx) not working as expected when I selected =

**Comment by jakeboone02** [comment]
I think all you have to do is include `operator` in your criteria for using the dual inputs.  Like this:

```tsx
import {
  ValueEditor as DefaultValueEditor,
  ValueEditorProps
} from "react-querybuilder";

const ValueEditor = (props: ValueEditorProps) => {
  const { field, value, handleOnChange, operator } = props; // <-- deconstruct `operator` from props

  if (field === "field1" && operator === 'between') { // <-- check for `operator === 'between'`
    const [val1, val2] = value === "" ? ["", ""] : value;

    return (
      <>
        <input
          type="text"
          value={val1}
          onChange={(e) => handleOnChange([e.target.value, val2])}
        />
        and
        <input
          type="text"
          value={val2}
          onChange={(e) => handleOnChange([val1, e.target.value])}
        />
      </>
    );
  }

  return <DefaultValueEditor {...props} />;
};

export default ValueEditor;
```

**Comment by vijayky** [comment]
It would be awesome if `between` and `not between` is available in default operator's list, then not everyone has to implement the same logic. just a thought...

**Comment by jakeboone02** [comment]
@vijayky - I could easily add `"between"` and `"notBetween"` to the `defaultOperators` list, but implementing the array-based value handling logic I think would be a little too specialized to include in the standard distribution. There are instructions here, and working examples linked, for using custom `ValueEditor` and `valueProcessor` functions to accomplish the desired result. I believe that would be sufficient for those who are required to implement a "between" rule.

**Comment by vijayky** [comment]
Yes, that's fine. Thank you for everything.

**Comment by jakeboone02** [comment]
@vijayky - actually I changed my mind and went ahead and added `between`/`notBetween` operators to the default set. See PR 
#225. `formatQuery` will also handle them by default, if the rule value is an array of length 2 or a string with exactly one comma that is not the first or last character.

**Comment by vijayky** [comment]
Awesome Jake! Thanks a lot...

**Comment by jakeboone02** [comment]
The `between` and `notBetween` operators are in the default list in [v3.12.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v3.12.0).
