### ISSUE TITLE
Is it possible to use input type field instead of select 

### ISSUE THREAD

**Issue by CodMonk** [react-querybuilder/react-querybuilder#212]
How can we use Field Type as input not the select ?

![image](https://user-images.githubusercontent.com/15674997/129248260-40bb462c-9e05-4870-b17c-410a54568a40.png)

**Comment by jakeboone02** [comment]
While I will caution that it doesn't actually sound like a good idea, you _can_ accomplish this with a custom `fieldSelector` component.  See [this codesandbox](https://codesandbox.io/s/agitated-sunset-324ml) for a live example.  A basic `<input>`-based custom component looks like this:

```tsx
import { ValueSelectorProps } from "react-querybuilder";

const FieldSelector = ({
  className,
  handleOnChange,
  options,
  title,
  value
}: ValueSelectorProps) => {
  return (
    <input
      className={className}
      title={title}
      value={value}
      onChange={(e) => handleOnChange(e.target.value)}
    />
  );
};

FieldSelector.displayName = "FieldSelector";

export default FieldSelector;
```

You can assign the custom component to the query builder using the `controlElements` prop:

```tsx
      <QueryBuilder
        fields={fields}
        onQueryChange={(q) => setQuery(q)}
        query={query}
        controlElements={{
          fieldSelector: FieldSelector
        }}
      />
```

Another thing I would recommend would be some sort of form validation on that element, so that even though the `<input>` is free-form, the user gets an indication of whether their input is valid or not.  You can add all that to the custom component.
