### ISSUE TITLE
How to add between operator

### ISSUE THREAD

**Issue by nageshwari17** [react-querybuilder/react-querybuilder#215]
Hi Team , I am using querybuilder in application . there is a requirement of setting range value from and to of Age , Year , etc 

How to add two select box with value field and get the range value in sql query . please help me with this . Thank you .

**Comment by jakeboone02** [comment]
Hi @nageshwari17.  I addressed this topic in #201.  [This codesandbox](https://codesandbox.io/s/angry-bardeen-c5tv0) demonstrates a simple two-`<input>` solution, and [this codesandbox](https://codesandbox.io/s/jolly-leftpad-m1m9x) uses `react-datepicker` to select a date range.  It would only require slight modifications to use `<select>`s instead of text inputs or date pickers.

**Comment by nageshwari17** [comment]
I think the above expample is working based on field . But its should work based on operator [this example not working as expected when I selected = ](https://codesandbox.io/s/cool-rain-rem57?file=/src/App.tsx)

**Comment by jakeboone02** [comment]
I think all you have to do is include `operator` in your criteria for using the dual inputs.  Like this:

```tsx
import {
  ValueEditor as DefaultValueEditor,
  ValueEditorProps
} from "react-querybuilder";

const ValueEditor = (props: ValueEditorProps) => {
  const { field, value, handleOnChange, operator } = props; // <-- deconstruct `operator` from props

  if (field === "field1" && operator === 'between') { // <-- check for `operator === 'between'`
    const [val1, val2] = value === "" ? ["", ""] : value;

    return (
      <>
        <input
          type="text"
          value={val1}
          onChange={(e) => handleOnChange([e.target.value, val2])}
        />
        and
        <input
          type="text"
          value={val2}
          onChange={(e) => handleOnChange([val1, e.target.value])}
        />
      </>
    );
  }

  return <DefaultValueEditor {...props} />;
};

export default ValueEditor;
```

**Comment by fasiha** [comment]
Thanks for the detailed explanation and code @jakeboone02!

This may seem like a pathological edge case but I'm actually interested: how would you handle the `between` case with two `input`s where *one* of the bounds is a value and the *other* is a field?

I mean, I can figure out how to replace one of the `input`s with a `select`—that's fine, but what I'm scratching my head about is, how can I fit this idea (one field and the other value) into the current field-vs-value `valueSources` paradigm? Is that just not possible with the current architecture? Or is there some clever workaround I'm not seeing?

Thank you again! I love the library and your constant support and improvements to it, really a beautiful jewel of open source!

**Comment by jakeboone02** [comment]
Wow, that's very kind of you to say! Thanks so much. I honestly don't get a ton of feedback about this library but at least I tend to assume that means it Just Works™.

Do you need a specific select to be for fields (e.g. just the first one), or should either of the selects be able to handle fields? Like, could you have fields/values, fields/fields, values/fields, or values/values? Or would only a subset of those combinations be applicable?

**Comment by fasiha** [comment]
> Do you need a specific select to be for fields (e.g. just the first one), or should either of the selects be able to handle fields?

The latter: my current implementation of `between` (using a home-grown library) allows users to select field vs value for either/both/neither bound so I’d love to preserve that functionality as I migrate to React Query Builder. Would full generality for `between`/`notBetween` need a big rethink?

> I tend to assume that means it Just Works

Definitely 1000% this! But also the very generous support you provide in these issues makes it that much more nice to use 😁 for example, I didn’t quite realize looking at the docs for `ValueEditor` that you could do cool things like in the examples above 💪

**Comment by jakeboone02** [comment]
Thanks again for the kind words! If there are any particularly helpful comments or examples you've come across, let me know in a [new issue for the documentation site](https://github.com/react-querybuilder/react-querybuilder.github.io/issues/new) and I can add a new [Tips & Tricks page](https://react-querybuilder.js.org/docs/category/tips--tricks). (Or if you really want, you can submit a PR to add one yourself!)

`formatQuery` can currently handle "between"/"notBetween" when either both elements are values or both are fields, but not one of each. Given the current API, the only way I can think to represent a more flexible `value` property would be something like this:

```ts
const rule: RuleType = {
  field: "f1",
  operator: "between",
  value: [
    { valueSource: "field", value: "f2" },
    { valueSource: "value", value: "14" },
  ],
};
```

You'd have `value` as an array, which is usually fine, but since the array elements are objects you'd need a custom `ValueEditor` and `valueProcessor` to handle it.

Discussion of the bigger issues this raises will continue in #317.

**Comment by fasiha** [comment]
> `formatQuery` can currently handle "between"/"notBetween" when either both elements are values or both are fields

Could I follow up on this point: I see how `between` on **values** works by splitting the value on commas, but could I confirm how `between` works on **fields**? I have a minimal example at https://codesandbox.io/s/heuristic-liskov-yyx9k1?file=/src/App.tsx where RQB outputs only the value rule, and ignores the field rule. I'm not sure where my misunderstanding lies. 

(And thank you for your enlightening comment about storing objects as `value`! I'll write more about that soon.)

**Edit** Ah I see that `formatQuery` can handle an array of fields:
```
      {
        field: "ticker",
        operator: "between",
        value: ["company", "price"],
        valueSource: "field"
      }
```
emits `ticker between company and price`, but the QueryBuilder doesn't seem to know there's a second field? I must be doing something kooky.

**Comment by jakeboone02** [comment]
You're not doing anything kooky. The default `ValueEditor` doesn't provide a way to select multiple fields for rules with `valueSource: "field"`, even for the "between" operator. That's why I said `formatQuery` could handle it but slyly avoided saying anything about `ValueEditor`. ;)

The reason it doesn't support that is because RQB would need to become more opinionated, and I don't really want to go down that path. For example, `ValueEditor` could display two `<select />`s when the operator is "between", but then it would have to pick a `value` structure (`"val1,val2"` or `["val1", "val2"]`) and it would also have to pick a fallback behavior for cases that don't meet the 2-element requirement like `value: null` or `value: "val1,"`.

**Comment by fasiha** [comment]
> The reason it doesn't support that is because RQB would need to become more opinionated, and I don't really want to go down that path

Ahh got it, thanks for bearing with me, makes total sense. This… actually leaves me a bit uncomfortable? In that, the UI allows users to build something that is silently ignored.

But no worries, thanks to your pointers, I now have RQB superpowers and can readily build a `between` for fields!

**Comment by jakeboone02** [comment]
> the UI allows users to build something that is silently ignored

This is definitely a shortcoming of the library. Maybe not a "bug" per se, but something we should address.

Congratulations on your superpowers!  🤣
