### ISSUE TITLE
Adding a default rule to the new group

### ISSUE THREAD

**Issue by vijayky** [react-querybuilder/react-querybuilder#221]
I am looking for an option to add a default rule (or may be the first rule) to the new group when created, instead of showing empty group. I looked into the code and found that _createRule_ and _createRuleGroup_ functions are called when +Rule or +Group buttons are clicked. 

I am thinking if a prop can be passed to receive onAddRule or onAddGroup button and provide default settings. 

Please share your thoughts.

**Comment by jakeboone02** [comment]
We could provide a Boolean prop that determines whether a rule is added by default when new groups are created, e.g. `addRuleToNewGroups={true}` then new groups would have a rule added upon creation (using the existing default settings for new rules).

Another option is to accept a `defaultRule` prop which would be added to new groups.

How would you imagine the API for `onAddRule` or `onAddGroup` working?  What values would each callback accept and return?

**Comment by vijayky** [comment]
> We could provide a Boolean prop that determines whether a rule is added by default when new groups are created, e.g. `addRuleToNewGroups={true}` then new groups would have a rule added upon creation (using the existing default settings for new rules).

I think I like the idea of have a `bool` flag and may be default value be `false` so that it would not change something for existing users. Adding a default rule may help put validation as you are thinking on one of the other tickets. If you have group with no rule it could also be a possible validation criteria. A group without rule does not create valid SQL syntax. 

> 
> Another option is to accept a `defaultRule` prop which would be added to new groups.
> 
> How would you imagine the API for `onAddRule` or `onAddGroup` working? What values would each callback accept and return?

Having a API would provide option to select fields for `onAddRule` (may be a field which is not on the rule list), operator based on the field's data type, validation logic etc. 
For `onAddGroup`, may help to select appropriate combinator/not flag or may restrict adding new group for a simple query builder interface. 

```javascript
onAddRule({fields: [field], parentGroup: {}, allCurrentRules: []}) : Rule object
onAddGroup({fields: [field], parentGroup: {}, allCurrentRules: []}) : RuleGroup object
```

both functions may return either `null` for default action or may return `Rule` or `RuleGroup`  per case above.
The object could be added to the rule tree, if a valid return object is provided. the return object may have ID populated, otherwise QueryBuilder may add it.

Just a thought....

**Comment by jakeboone02** [comment]
> > We could provide a Boolean prop that determines whether a rule is added by default when new groups are created, e.g. `addRuleToNewGroups={true}` then new groups would have a rule added upon creation (using the existing default settings for new rules).
> 
> I think I like the idea of have a `bool` flag and may be default value be `false` so that it would not change something for existing users. Adding a default rule may help put validation as you are thinking on one of the other tickets. If you have group with no rule it could also be a possible validation criteria. A group without rule does not create valid SQL syntax.

Yeah, I like the idea of a Boolean (default `false`) prop to automatically add a rule to new groups. Should that include the root group? For example, if the initial query object has an empty `rules` array, should a rule be added to it during the first render?

> 
> > Another option is to accept a `defaultRule` prop which would be added to new groups.

Thinking about this more, I don't think we need a `defaultRule` prop. We already have `getDefaultField` and `getDefaultValue`, the only thing missing is `getDefaultOperator`. Not sure if I actually want to implement that or not. I'll think about it some more and decide later.

> > How would you imagine the API for `onAddRule` or `onAddGroup` working? What values would each callback accept and return?
> 
> Having a API would provide option to select fields for `onAddRule` (may be a field which is not on the rule list), operator based on the field's data type, validation logic etc. For `onAddGroup`, may help to select appropriate combinator/not flag or may restrict adding new group for a simple query builder interface.

FYI, you can prevent users from adding sub-groups to the query builder by passing `controlElements={{ addGroupAction: () => null }}`. That prevents the "+Group" button from appearing, forcing a flat, rule-only hierarchy.

> 
> ```js
> onAddRule({fields: [field], parentGroup: {}, allCurrentRules: []}) : Rule object
> onAddGroup({fields: [field], parentGroup: {}, allCurrentRules: []}) : RuleGroup object
> ```
> 
> both functions may return either `null` for default action or may return `Rule` or `RuleGroup` per case above. The object could be added to the rule tree, if a valid return object is provided. the return object may have ID populated, otherwise QueryBuilder may add it.
> 
> Just a thought....

I would alter the shape of those functions. The `fields` param is already known to the user, because they passed it in to `<QueryBuilder />`. `allCurrentRules` should be a `RuleGroupType` object representing the current query (before the rule is added), not an array. The `parentGroup` should probably just be `parentId` so they can find the group within the `allCurrentRules` object. (We could expose the `findRule` utility function to help with that.)

Actually, I think the user probably just needs the `RuleType` object that _would_ be added, the `parentId`, and the current `query`. The function should return a `RuleType` object that gets added instead of the one that `QueryBuilder` originally intended to add, or a falsy value to cancel the action entirely. Ditto for the `onAddGroup` callback, but with `RuleGroupType`.

Example:

```ts
interface QueryBuilderProps {
  // ...
  onAddRule?(rule: RuleType, parentId: string, query: RuleGroupType): RuleType | false;
  onAddGroup?(ruleGroup: RuleGroupType, parentId: string, query: RuleGroupType): RuleGroupType | false;
  // ...
}
```

Thoughts?

**Comment by vijayky** [comment]
> Should that include the root group?

Yes, please. It would be helpful to show the default rule that way.

> Regarding `getDefaultOperator`

I think currently you are showing first operator is default, and I guess that should be enough but having a feature is not bad at all. 

>  Preventing adding a group

By passing a React component that returns null JSX, that's a clever idea, I did not think of that. 
Per you Api signature, you are providing one more way to return `falsy` value from `onAddGroup` and prevent adding a new group.

> Regarding Api

I think I like you thoughts restructuring the method signatures. :+1:

**Comment by jakeboone02** [comment]
I started implementing these features in #224.  I changed one thing:  when `addRuleToNewGroups` is set to `true`, a new rule will _not_ be automatically added to the root group unless a `query` prop is not passed in. That way it will respect existing queries that have intentionally empty `rules` arrays.

**Comment by vijayky** [comment]
Thank you..
