### ISSUE TITLE
Ability to get the input type on generated rules from JSON.

### ISSUE THREAD

**Issue by balboFK** [react-querybuilder/react-querybuilder#226]
Hello!
Thanks for the awesome library!

I was wondering if it's somehow possible to get the "inputType" on the final generated rule object when exporting to JSON.

```
const fields = [
     { name: 'description', label: 'Description', inputType: 'string' },
     { name: 'price', label: 'Price', inputType: 'number' },
]

{
    "rules": [
        {
            "field": "description",
            "value": "M4",
            "operator": "startswith",
            "type": "string" // this being the prop that was given to "inputType"
        },
        {
            "field": "price",
            "value": "579,99",
            "operator": "greaterthan",
            "type": "number" // this also being the prop that was given to "inputType"
        },
    ],
    "combinator": "and",
    "not": false
}
```

Also, is it possible to remove the "not" property from the object when using 'formatQuery'?
Thanks!

**Comment by jakeboone02** [comment]
I don't want to add `inputType` to the default export since it's tied to the Field object and not the Rule, and would therefore be redundant, but you can add `inputType` to the query yourself with the following code. (I haven't actually tested it but it should be pretty close.) It's TypeScript but if you need a plain JavaScript version I can strip out the type-related stuff for you.

```ts
import { RuleGroupType, RuleType } from 'react-querybuilder';

const fields = [
  { name: 'description', label: 'Description', inputType: 'string' },
  { name: 'price', label: 'Price', inputType: 'number' }
];

const processRule = (r: RuleType): RuleType & { inputType?: string } => ({
  ...r,
  inputType: fields.find((f) => f.name === r.field)?.inputType
});

const processGroup = (rg: RuleGroupType): RuleGroupType => ({
  ...rg,
  rules: rg.rules.map((r: RuleType | RuleGroupType) => {
    if (r['field' as 'id']) {
      return processRule(r as RuleType);
    }
    return processGroup(r as RuleGroupType);
  })
});

const result = processGroup(query);
```

To remove the `not` property, just do this:

```ts
JSON.stringify(query, ['rules', 'field', 'value', 'operator', 'combinator']);
```

That will stringify your query but only export the properties listed in the second argument array.  This is exactly how the `"json_without_ids"` format works, but it includes the `not` property.

**Comment by balboFK** [comment]
Hey @jakeboone02 , thanks for the fast reply and help! Works like a charm.
The guys from the backend here are giving you a shoutout, since they will not need to change anything on their side to achieve what we we're hoping for!

Thanks for the help and for the amazing library, you rock.

**Comment by jakeboone02** [comment]
Aw, thanks! I really appreciate that. Glad to help.
