### ISSUE TITLE
How do you validate queries at the backend side?

### ISSUE THREAD

**Issue by mylawacad** [react-querybuilder/react-querybuilder#236]
Thank you for the outstanding query builder.

Curious is there any best practice on how to validate the resulting query on the backend side. It is a bit scary to hit the database with a custom query not validated against the rules. I tried to install and import the module at the NodeJs side (so to use formatQuery and defaultValidator at the backend side) , but it seems that I can't export these separately and module requires react.

Appreciate if you could point me to the right way.

**Comment by jakeboone02** [comment]
Hey @mylawacad, thanks for the compliment. We're glad you find the library useful.

You shouldn't have to worry too much about the output of `formatQuery`, especially if you use the "parameterized" format with bind variables. `formatQuery` only produces a `WHERE` clause, so there's very little risk of it producing anything dangerous on its own (but we'd _love_ to have a security audit done just to be sure).

We're currently working on v4.0.0, which, if all goes well, will not require React on the server side if you're just using `formatQuery`. It will also include a new "parameterized_named" format that will facilitate named bind variables instead of an anonymous "?" like the "parameterized" format produces.

You can try the latest 4.0 beta release with `npm i react-querybuilder@4.0.0-beta.5` or `yarn add react-querybuilder@4.0.0-beta.5`.  Documentation for v4.0 is [here](https://react-querybuilder.js.org/).

**Comment by jakeboone02** [comment]
@mylawacad I just released [v4.0.0-beta.6](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.0.0-beta.6) which does not require `react` on the server side if you're just using the `formatQuery` function. Import it like this: `import formatQuery from 'react-querybuilder/dist/formatQuery'`.

**Comment by mylawacad** [comment]
Hi @jakeboone02  Thank you very much for taking a look into this for me. Let me try this out. 

Really an outstanding repository. Thank you once again.
