### ISSUE TITLE
New valueEditorType: date

### ISSUE THREAD

**Issue by balboFK** [react-querybuilder/react-querybuilder#238]
Hello everyone.
Would it be possible to add this new valueEditorType to the defaults?
Lets say that I want to filter between two dates, like 'initialDate' and 'finalDate', to find if a value is on this time frame.

On my case, this would be easily solved with a new valueEditorType, so I would be able to pass it to my custom valueEditor and check over it.

For now I'm modifying the default type like bellow and checking on my valueEditor. 
```ts
type NewField = Omit<Field, 'valueEditorType'> & {
  valueEditorType?: 'text' | 'select' | 'checkbox' | 'radio' | 'datePicker' | null
}

const queryBuilderFields: NewField[] = [
  { name: 'orderType', label: 'Type', inputType: 'string', operators: stringOperators },
  { name: 'orderInclusionDate', label: 'Inclusion Date', inputType: 'string', operators: stringOperators, valueEditorType: 'datePicker' }
]


// on my custom valueEditor I just do: 

switch (type) {
  case 'text':
    return <Input />
  case 'datePicker':
    return <DatePicker />
}
```

Is this maybe a plausible addition?
Thanks!

_PS: the examples are very basic just consider them as a way to pass the idea of the concept!_

**Comment by jakeboone02** [comment]
> **EDIT 2022-01-19:** The ["Custom components with fallback" page on the documentation site](https://react-querybuilder.js.org/docs/tips/custom-with-fallback) now demonstrates a custom component using `react-datepicker`, as I hinted I would do below. Also, v4 was released a few weeks ago.

Hi, @balboFK! The easiest way to provide a date picker is to use the `inputType` property rather than `valueEditorType`. Using `inputType: "date"` for a field will trigger the browser's native date picker when that field is selected. This works on Chrome, Firefox, Safari, and Edge, but not IE.

If you don't want to rely on the browser's native date picker, then you'll need to use a custom component anyway since `react-querybuilder` doesn't know which date picker library you want to use. The most popular in the React world is probably [`react-datepicker`](https://reactdatepicker.com/), and I may sometime in the future provide an official `ValueEditor` component that implements it. For now, though, this library will be agnostic about date pickers.

I'd also like to bring your attention to the [v4.0 beta release](/react-querybuilder/react-querybuilder/releases/tag/v4.0.0-beta.5). The documentation for v4.0 is [here](https://react-querybuilder.js.org). I'm working on the "Tips & Tricks" section and plan to include some tips on using the "between" operator and `react-datepicker` (see [this issue](/react-querybuilder/react-querybuilder.github.io/issues/2)). You may also find [this page](https://react-querybuilder.js.org/docs/tips/custom-with-fallback) about custom components that fall back to the default components helpful.

**Comment by balboFK** [comment]
Hello @jakeboone02, thanks for the reply! Right now my implementation is covering our needs, I will check out the recomended links and take a read on the topics. 

I will be looking up to see the future implementation for the date picker.

On my case it looks like this, if someone is interested, the implementation is working for the 'between' type, if you don't want to use between just check for the "type":

```ts
export const QueryBuilderInput = ({
  operator,
  value,
  handleOnChange,
  title,
  type,
  inputType,
  className,
  values
}: NewValueEditorProps): JSX.Element => {
  if (operator === 'isnull' || operator === 'isnotnull') {
    return null
  }

  if (operator === 'between' || operator === 'notbetween') {
    const [value1, value2] = value === '' ? ['', ''] : value

    if (type === 'datePicker') {
      return (
        <>
          <DatePicker
            style={{ margin: '.25rem' }}
            placeholder='Data inicial'
            value={value1 ? dayjs(value1) as moment.Moment : null}
            onChange={(dateObject) => handleOnChange([dateObject.format('YYYYMMDD'), value2])}
          />
          <DatePicker
            style={{ margin: '.25rem' }}
            placeholder='Data final'
            value={value2 ? dayjs(value2) as moment.Moment : null}
            onChange={(dateObject) => handleOnChange([value1, dateObject.format('YYYYMMDD')])}
          />
        </>
      )
    }
}
```

Also looks very good!

![image](https://user-images.githubusercontent.com/87539237/143612079-29d06d79-8391-4d80-b273-4115f820b86f.png)

Thanks again @jakeboone02 !

**Comment by jakeboone02** [comment]
Great! Looks like everything's covered for now...mind if we close this issue?

**Comment by balboFK** [comment]
Closing!
