### ISSUE TITLE
Multiple rule buttons to allow dynamic fields list

### ISSUE THREAD

**Issue by phrilrm** [react-querybuilder/react-querybuilder#263]
Thanks for creating this great library!

Not sure if the title describes my issue effectively but I hope I can here.
I have a situation where I would like to filter the fields array on a per-rule basis. That's to say, if I would like to be able to have two different rule buttons, which would add a rule with different field values. One way I imagined doing this was by adding another rule button via `addRuleAction` the `controlElements` prop like such:
```
<QueryBuilder
  ...
  fields={fields}
  controlElements={{
          ...
          addRuleAction: (props) => {
            return (
              <>
                <button
                  className={props.className}
                  title={props.title}
                  onClick={(e) => {
                    return props.handleOnClick(e);
                  }}
                >
                  Add Rule 1
                </button>
                <button
                  className={props.className}
                  title={props.title}
                  onClick={(e) => {
                    return props.handleOnClick(e);
                  }}
                >
                 Add Rule 2
                </button>
              </>
            );
            ...
```
This renders the two buttons but of course clicking either just adds a new row containing the same fields array.
Currently my fields array looks like this (a very shortened version):
```
const fields = [
  { name: 'one', label: 'one' },
  { name: 'two', label: 'two' },
  { name: 'three', label: 'three' },
  { name: '1', label: '1' },
  { name: '2', label: '2' },
  { name: '3', label: '3' },
];
```
on clicking `Add Rule 1` I would get the text versions of the fields and the numeric with `Add Rule 2`.

Is there a way to go about this? Alternatively I could drop the multiple rule buttons and have a different structure with dependent fields ala:
`Type Selector -> Fields -> Operator -> Value` where Type Selector would be a dropdown with 'Text' or 'Numeric' and would filter the fields array. I'm just not sure how to go about this either. :-/

Are either of these approaches possible with this library?

**Comment by jakeboone02** [comment]
Yeah, there are definitely a few ways you could achieve what you're trying to do. The first option, with the extra "Add Rule" button, is doable but requires more manual query management. For example, instead of calling the `handleOnClick` prop from the new button, you would call an external, custom function that takes the existing query object and adds a new rule with the appropriate `field` pre-selected based on which button was clicked. _But_, you'd also have to take the `path` of the rule group header where the button was located so the function would know where to insert the new rule. The function would then recursively search the `rules` arrays within the query object to find the correct `path`, and set your query state variable. That would be passed in as the new `query` prop to `<QueryBuilder />`.

I think the other option you suggested would be easier. You could provide a wrapper around the default `fieldSelector` component that allows the user to choose text or numeric for each rule, then filter the available field options based on that choice.

I've demonstrated the latter technique in [this codesandbox example](https://codesandbox.io/s/react-querybuilder-enhanced-field-selector-xx97y?file=/src/App.tsx). Let me know if you would rather have an example of the former, more complicated technique. I've done something similar recently so it wouldn't be too much trouble.

**Comment by phrilrm** [comment]
Thank you very much for your detailed answer! I actually think the second example is the way to go. Much more simple. I was pretty much able to reuse your code in the codesandbox example above, which saved me a few hours! 👍 But it is great to hear that the library is flexible enough to do it both ways. Thanks again! 🙏

**Comment by jakeboone02** [comment]
That's great to hear. Happy New Year!
