### ISSUE TITLE
Is there any way to hide already selected filter value

### ISSUE THREAD

**Issue by AnwinShaji** [react-querybuilder/react-querybuilder#302]
Hi, 
I'm new to this queryBuilder. In my project I need to hide already selected field value from the dropdown. 

Eg: If i select field as "Country"  and value a "US", the next time I select field as "Country" then show the dropdown without US in that list

**Comment by jakeboone02** [comment]
Hmm, so you need each rule value to be unique for each field? That will probably require a custom `ValueEditor` component, but only to limit the options and not for the actual rendering. Let me see what I can come up with.

**Comment by jakeboone02** [comment]
OK, I think I've got something that will work for you. ~~A [demo codesandbox is here](https://codesandbox.io/s/react-query-builder-unique-rule-values-jjgevu?file=/src/App.tsx).~~

_Updated sandbox 2025-03-27: https://codesandbox.io/p/devbox/8mc4lz?file=%2Fsrc%2FCustomValueEditor.tsx_

Of note:

- I set the `controlElements.addGroupAction` prop to a function that always returns `null`. This forces a flat rule list (rule groups cannot be added since the button isn't rendered). This step is not strictly necessary, it just makes the "used values" collection easier.
- I defined a property in the `fields` array (`forceUnique`) to identify which fields will be forced to have unique values among rules with the same field. I applied this property to the `country` and `country2` fields.
- I created a `CustomValueEditor` component that renders the default `ValueEditor` when `forceUnique` is not `true` for the current rule's field.
- If `forceUnique` _is_ `true` for the current rule's field, `CustomValueEditor` gets the list of values from the field's configuration and filters out all the values that have been selected in other rules (ignoring the rule's current value). For this I had to add the `query` to the `context` prop since `ValueEditorProps` doesn't include the entire query (maybe it should...hmmm).
- I assigned a function to the `getDefaultValue` prop that chooses the first available value in the field's `values` list after filtering out already-used values.

The simplest way to see it in action is to click the "+Rule" button several times. You'll see that each new rule has a different value (courtesy of the `getDefaultValue` function). Also, change one of the fields to "Country 2" and notice that, although it shares a `values` list with the Country field, the uniqueness of the values does not apply to those rules.

Hope that helps!

`App.tsx`:

```tsx
import { useState } from 'react';
import {
  NameLabelPair,
  QueryBuilder,
  RuleGroupType,
  RuleType,
} from 'react-querybuilder';
import 'react-querybuilder/dist/query-builder.scss';
import { CustomValueEditor } from './CustomValueEditor';
import { fields } from './fields';

export default function App(): JSX.Element {
  const [query, setQuery] = useState<RuleGroupType>({
    combinator: 'and',
    rules: [],
  });

  return (
    <div>
      <QueryBuilder
        context={{ query }}
        fields={fields}
        query={query}
        onQueryChange={q => setQuery(q)}
        controlElements={{
          addGroupAction: () => null,
          valueEditor: CustomValueEditor,
        }}
        getDefaultValue={r => {
          if (r.field !== 'country') return '';
          const usedValues = (query.rules as RuleType[]).map(
            r => r.value as string
          );
          return (fields.find(f => f.name === r.field)!
            .values! as NameLabelPair[]).filter(
            c => !usedValues.includes(c.name)
          )?.[0]?.name;
        }}
      />
    </div>
  );
}
```

`CustomValueEditor.tsx`:

```tsx
import {
  NameLabelPair,
  RuleType,
  ValueEditor,
  ValueEditorProps,
} from 'react-querybuilder';
import { fields } from './fields';

const getValues = (
  ruleArray: RuleType[],
  rule: Pick<RuleType, 'field' | 'value'>
) => {
  const usedValues = ruleArray
    .filter(r => r.field === rule.field)
    .map(r => r.value as string);
  return (fields.find(f => f.name === rule.field)!
    .values! as NameLabelPair[]).filter(
    c => c.name === rule.value || !usedValues.includes(c.name)
  );
};

export const CustomValueEditor = (props: ValueEditorProps) => {
  if (props.fieldData.forceUnique) {
    const { field, value } = props;
    const values = getValues(props.context.query.rules, {
      field,
      value,
    });
    return <ValueEditor {...props} values={values} />;
  }

  return <ValueEditor {...props} />;
};
```

`fields.ts`

```ts
import { Field, NameLabelPair } from 'react-querybuilder';

const largestCountriesByPopulation: NameLabelPair[] = [
  { name: 'cn', label: 'China' },
  { name: 'in', label: 'India' },
  { name: 'us', label: 'United States' },
  { name: 'id', label: 'Indonesia' },
  { name: 'pk', label: 'Pakistan' },
  { name: 'br', label: 'Brazil' },
  { name: 'ng', label: 'Nigeria' },
  { name: 'bd', label: 'Bangladesh' },
  { name: 'ru', label: 'Russia' },
  { name: 'mx', label: 'Mexico' },
];

export const fields: Field[] = [
  {
    name: 'country',
    label: 'Country',
    valueEditorType: 'select',
    values: largestCountriesByPopulation,
    forceUnique: true,
  },
  {
    name: 'country2',
    label: 'Country 2',
    valueEditorType: 'select',
    values: largestCountriesByPopulation,
    forceUnique: true,
  },
  { name: 'city', label: 'City', inputType: 'text' },
];
```

**Comment by AnwinShaji** [comment]
Hi @jakeboone02 , thanks for the fast reply and helping me on this.
