### ISSUE TITLE
Value is not returning

### ISSUE THREAD

**Issue by anwin-aot** [react-querybuilder/react-querybuilder#330]
Hi @jakeboone02 ,

I was going through  https://codesandbox.io/embed/2y1u5?codemirror=1 After selecting "field 2"  from first select box, and select a value from second select box, library is not returning second select box selected value. Can you please provide me a solution for this.

![image](https://user-images.githubusercontent.com/96901218/173814650-8fc56874-1625-46fd-a0d2-75ce3d2b4910.png)

**Comment by jakeboone02** [comment]
First off, this example is using a quite outdated version of RQB. I suggest upgrading to the latest. There are no breaking changes for this implementation other than styling (v4+ uses flexbox), so it should work exactly the same after the upgrade with no code changes.

It looks like the issue is that the second select is storing its state locally (with `useState`) instead of using the RQB API method `handleOnChange`. So the `nameURL` value stays scoped to the specific element that created it instead of getting included in the query object.

What's going to complicate this is if you _do_ want to use `handleOnChange`, you'll need to find a way to store both the `nameURL` value _and_ the operator selection in the `operator` property of the rule. You can do this with arrays or comma-separated strings, you just have to make sure your custom operator selector can handle all cases. Also, setting the `defaultOperator` property on the relevant fields will help (this requires v4).

You can also reduce the amount of code in the `FieldSelector` component (if you upgrade to v4) by using `OptionGroup<Field>[]` to define your fields instead of manually re-grouping them in the selector component. It would look like this:

```ts
const fields: OptionGroup<Field>[] = [
  {
    label: "First Group",
    options: [
      {
        name: "field1",
        label: "Field 1",
      },
      {
        name: "field2",
        label: "Field 2",
        type: "cact",
      },
    ],
  },
  {
    label: "Second Group",
    options: [
      {
        name: "field3",
        label: "Field 3",
      },
      {
        name: "field4",
        label: "Field 4",
      },
    ],
  },
];
```

**Comment by anwin-aot** [comment]
Thank you, for providing solution
