### ISSUE TITLE
IndependentCombinators: true > Type 'true' is not assignable to type 'false'

### ISSUE THREAD

**Issue by Laura-Urb** [react-querybuilder/react-querybuilder#342]
Hi! I'm new using this library and I'm trying out in my react + typescript project
I need that combinators were independent but I have this problem that  I can't set independentCombinators={true}
Do I'm missing something?
![aaa](https://user-images.githubusercontent.com/63360295/177539467-63f394b3-5710-43c0-8e39-2bc01b72c991.png)
![bbb](https://user-images.githubusercontent.com/63360295/177539470-4de0ac03-0b07-4255-85d2-d06523957969.png)
![ccc](https://user-images.githubusercontent.com/63360295/177539472-0b193eea-143c-4c8b-a5f7-33bbc282e89f.png)

**Comment by jakeboone02** [comment]
Hi, @Laura-Urb! I can't see from your screenshots, but it looks like your `query` object is of type `RuleGroupType`. When the `independentCombinators` prop is `true`, `query` (or `defaultQuery`) must be type `RuleGroupTypeIC`.

The difference between the types is that for the `IC` variant, the combinator values reside between each rule in the `rules` array instead of on the `combinator` property, like this:

```ts
const query: RuleGroupTypeIC = {
  rules: [
    { field: 'lastName', operator: '=', value: 'Vai' },
    'and',
    { field: 'firstName', operator: '=', value: 'Steve' },
  ],
};
```

I apologize for the lack of documentation on that. I think the [TypeScript page](https://react-querybuilder.js.org/docs/typescript#rules-and-groups) is really all we’ve got at the moment. I’ll get on that soon!

**Comment by jakeboone02** [comment]
Oh, I forgot to mention: the [`showCombinatorsBetweenRules` prop](https://react-querybuilder.js.org/docs/api/querybuilder#showcombinatorsbetweenrules) has the same visual effect as `independentCombinators` (i.e. a combinator selector appears between each pair of rules), but the `query` object can still be `RuleGroupType`.

The only weird thing about that is if you have more than two rules in a group, and therefore more than one combinator selector, selecting a different combinator in one of the drop-down lists will update _all_ the combinator selectors in that group to the same value. It behaves that way because with `RuleGroupType` there's only one `combinator` value for each group, so all the selectors must be in sync even if they _appear_ to be independent.

**Comment by Laura-Urb** [comment]
Thank you so much for the help!! That was excatly my problem (wrong type)

> Hi, @Laura-Urb! I can't see from your screenshots, but it looks like your `query` object is of type `RuleGroupType`. When the `independentCombinators` prop is `true`, `query` (or `defaultQuery`) must be type `RuleGroupTypeIC`.
> 
> The difference between the types is that for the `IC` variant, the combinator values reside between each rule in the `rules` array instead of on the `combinator` property, like this:
> 
> ```ts
> const query: RuleGroupTypeIC = {
>   rules: [
>     { field: 'lastName', operator: '=', value: 'Vai' },
>     'and',
>     { field: 'firstName', operator: '=', value: 'Steve' },
>   ],
> };
> ```
> 
> I apologize for the lack of documentation on that. I think the [TypeScript page](https://react-querybuilder.js.org/docs/typescript#rules-and-groups) is really all we’ve got at the moment. I’ll get on that soon!
