### ISSUE TITLE
How to implement sql option

### ISSUE THREAD

**Issue by janajay** [react-querybuilder/react-querybuilder#36]
There is no guide for getting the json into sql schema.

**Comment by miphe** [comment]
@janajay Could you give example output you'd be expecting?

**Comment by CharlyJazz** [comment]
@janajay  Hahahaha wow

**Comment by qubbit** [comment]
@janajay You can do this quite simply by using a few related tables.

Basically the tables are rules, rulesets (aka rulegroups), and values if you're supporting multiple values otherwise you can use the rules table to store that rule's value. To support the recursive nesting feature of a ruleset, you need a parent_id column to refer back to its parent.

I have done this in a production setting. Hopefully I can open-source it soon.

**Comment by jakeboone02** [comment]
@qubbit - did you ever manage to open-source your solution?

**Comment by jakeboone02** [comment]
I know this issue is over two years old, but I'd like some feedback on the PR I just opened (#95) that adds a `formatQuery` function to output a SQL `WHERE` clause for a given query.
