### ISSUE TITLE
Drag and drop issues moving a rule to a sibling group

### ISSUE THREAD

**Issue by dsalisbury** [react-querybuilder/react-querybuilder#360]
Hey! Love the library, thanks for making it and building such versatility!

I found a bug with dragging and dropping, which seems to manifest in ways approximately along the lines of:

1. Make a parent rule group with two child groups
2. Add a rule to each child
3. Try to drag the rule from the first child to the second child and watch it fail
4. Try the opposite and see it succeed, so now child1 has two rules
5. Try to drag the second rule from the first child into the second child, see that the order rotates
6. Drag a rule from the first child to the parent group, then drag it from there to the second child and see it succeed

Here's a recording of me playing around with it -- but I was a little unplanned in what I was doing so some drags don't actually do anything. 

https://user-images.githubusercontent.com/173081/187843831-95c329f0-a64b-4d7d-a4f2-a9b8d75aa4f4.mp4

**Comment by jakeboone02** [comment]
Thanks for the kind words! But...ugh. This type of bug coming up was kind of a big fear of mine, because the [code that manages that feature](https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/react-querybuilder/src/utils/queryTools.ts#L134-L219) is hard to grok for me (and I wrote it!). Seems like it should be simple, right? Just remove the rule/group from its original location and reinsert it where the user dropped it. But between the recursive/hierarchical nature of the query structure and having to support `independentCombinators`, it gets hairy pretty fast.

Anyway, enough whining! Could you do me a favor? If you could write up some tests for these particular moves using the `move` function exported from `react-querybuilder`, that would be a tremendous help. You can use [this codesandbox](https://codesandbox.io/s/hardcore-moon-cprm9c?file=/src/App.test.ts) as a template. I've already added a basic example test which takes a query with two rules and moves the second one up to the first position:

```ts
import { move } from 'react-querybuilder';

it('works', () => {
  expect(
    move(
      {
        combinator: 'and',
        rules: [
          { field: 'f1', operator: '=', value: 'v1' },
          { field: 'f2', operator: '=', value: 'v2' },
        ],
      },
      [1],
      [0]
    )
  ).toEqual({
    combinator: 'and',
    rules: [
      { field: 'f2', operator: '=', value: 'v2' },
      { field: 'f1', operator: '=', value: 'v1' },
    ],
  });
});
```

You should only need to use the first three arguments for `move`, which are 1) the original query object, 2) the original `path`, and 3) the new `path` (what the new path would be _before_ the move--this gets tricky when moving rules down). `move` returns the new query object after relocating the rule/group so use `toEqual` to see if it passes.

Paths are just a number array representing the rule/group's position in the hierarchy, e.g. `[]` is the root group, `[0]` is the first rule, `[1]` is the second rule. `[1, 2]` would be the third rule within a group that occupies the second position at the root level. Hope that makes sense. This might help:

```jsonc
{
  "path": [], // root group
  "rules": [
    {
      "path": [0], // first subgroup
      "rules": [
        { "path": [0, 0] }, // first rule in first subgroup
        { "path": [0, 1] } // second rule in first subgroup
      ]
    },
    {
      "path": [1], // second subgroup
      "rules": [
        { "path": [1, 0] }, // first rule in second subgroup
        { "path": [1, 1] } // second rule in second subgroup
      ]
    }
  ]
}
```

To test step 3 from your sequence above, you would use `move(query, [0, 0], [1, 0])` (or maybe `move(query, [0, 0], [1, 1])` depending on where in the second group the rule should go--first position or last).

**Comment by dsalisbury** [comment]
I'm working on tests to plumb the depths in search of some weird edge cases

A general feeling from what I've been playing with lately is that it seems like there might be some sort of off-by-one going on

For instance, I want to swap the order of these two top-level combinators:

```const query = {
          combinator: 'and',
          rules: [
            {
              combinator: 'and',
              rules: [
                { field: 'f1', operator: '=', value: 'v1' },
                { field: 'f2', operator: '=', value: 'v2' },
              ],
            },
            {
              combinator: 'and',
              rules: [],
            },
          ],
        }
```

issuing `move(query, [0], [1])` results in no change, while `move(query, [0], [2])` results in the groups swapping

**Comment by jakeboone02** [comment]
Yeah, sorry, I forgot about the other complication which is the coordination among the dragged element `path`, the drop zone `path`, the neighboring elements (if any), and the `move` logic. The `Rule`-as-drop-zone code is [here](https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/dnd/src/internal/hooks/useRuleDnD.ts#L48-L80) and the `RuleGroup`-as-drop-zone code is [here](https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/dnd/src/internal/hooks/useRuleGroupDnD.ts#L49-L81).

**Comment by dsalisbury** [comment]
I've made a bunch of tests in https://codesandbox.io/s/stoic-jones-iodrbq?file=/src/App.test.ts

I was playing around with this with a team mate today and we find this line to be mysteriously subtracting 1 or 2 from the target path's insertion index at the point of common ancestry -- but we can't figure out why this is happening.

oldPath and newPath come into the move function from the dnd event handler as the right values, but then after the transformation above, parentToInsertInto ends up being the wrong thing.

https://github.com/react-querybuilder/react-querybuilder/blob/main/packages/react-querybuilder/src/utils/queryTools.ts#L183

**Comment by jakeboone02** [comment]
Thanks for doing that! I'll start digging into the issue soon. Got a few kinks to work out in the v5 alpha first, then I'll hop on this one.

**Comment by jakeboone02** [comment]
@dsalisbury - I think I've got this fixed. Can you manually test with [this codesandbox](https://codesandbox.io/s/react-querybuilder-dnd-example-forked-obzo86?file=/src/App.tsx)? It uses the latest builds from #367.

**Comment by dsalisbury** [comment]
Hey @jakeboone02

The codesandbox looks good, thanks for fixing it!
