### ISSUE TITLE
Ant Design multiselect has a strange empty state

### ISSUE THREAD

**Issue by fasiha** [react-querybuilder/react-querybuilder#388]
We noticed an interesting edge case in React Query Builder + Ant Design and I wanted to check if it's something that's intentional or if it's a known issue.

This Code Sandbox demonstrates the issue https://codesandbox.io/s/gifted-mccarthy-dt4qrp the multiselect initializes with the first value selected, but if I remove it, the empty multiselect has a ghost empty string option selected.

![rbq-demo](https://user-images.githubusercontent.com/37649/196762631-806abc4d-cf4c-46f5-8c6a-b1469867630f.gif)

When we export this to JsonLogic for example, there's no rule for this, indicating that React Query Builder correctly treats the multiselect as non-existent, but from a UI perspective this is not ideal. I see in https://ant.design/components/select/ that the Ant multiselect seems to handle an empty multiselect just fine, so thought to check here.

**Comment by jakeboone02** [comment]
Definitely not intentional. Looks like a bug with the way the component handles empty strings when it expects a comma-separated list. If you make `value` an array, it seems to work as expected.

I copied your CodeSandbox to [StackBlitz here](https://stackblitz.com/edit/react-ts-wsbt4v?file=App.tsx) (I was having trouble with CS) and upgraded RQB to the latest v5 alpha just to make sure it wasn't already resolved (it wasn't).

![image](https://user-images.githubusercontent.com/366438/196785893-9f7e440f-41d8-4074-82cf-2175e18827e7.png)

The first rule's default `value` is an empty string and the second rule's is an empty array. The second rule behaves as expected no matter what you do but the first exhibits the bug you identified.

I also noticed that for the empty string case, if you click the X to remove the empty option it actually converts the value to an empty array and then behaves correctly after that. That conversion shouldn't happen; it should stay an empty string and be displayed properly as a completely empty input field.

Thanks for the bug report! I'll fix it before 5.0 is released, which will be soon.

**Comment by jakeboone02** [comment]
@fasiha #389 has a [version of your CodeSandbox using the latest build](https://codesandbox.io/s/crazy-ace-qmkcbb) of RQB and the antd compatibility package. Can you try it out and let me know if it resolves the issue?

**Comment by fasiha** [comment]
> @fasiha #389 has a [version of your CodeSandbox using the latest build](https://codesandbox.io/s/crazy-ace-qmkcbb) of RQB and the antd compatibility package. Can you try it out and let me know if it resolves the issue?

Thanks Jake! Looks perfect 🙏!
