### ISSUE TITLE
support for IF, ELSE, THEN statements.

### ISSUE THREAD

**Issue by Sax-Yusuph** [react-querybuilder/react-querybuilder#391]
hi, thank you for the great library.
can we have support  for IF, ELSE and THEN combinators
just as we currently have AND and OR...
2. or is there a way to achieve this at the moment?

<img width="669" alt="Screenshot 2022-10-22 at 9 36 42 PM" src="https://user-images.githubusercontent.com/57273445/197361456-6d8b998d-1162-489f-9427-5c047d9ce80a.png">

**Comment by jakeboone02** [comment]
Hi, Sax. There are two parts to my answer.

### Part 1 aka "Yes"

You can define custom combinators like this:

```tsx
const combinators: NameLabelPair[] = [
  { name: 'if', label: 'IF' },
  { name: 'then', label: 'THEN' },
  { name: 'else', label: 'ELSE' },
];

export const App = () => {
  return (
    <QueryBuilder
      fields={fields}
      combinators={combinators} // <-- assign to the `combinators` prop
      query={query}
      onQueryChange={q => setQuery(q)}
    />
  );
}
```

[Here's a CodeSandbox demonstration](https://codesandbox.io/s/dank-smoke-ti9qot?file=/src/App.tsx).

### Part 2 aka "You probably shouldn't"

It will be difficult to enforce the right structure for those particular combinators because this query builder only builds the "if" part with conditions. The "then" and "else" parts are actions/results rather than conditions.

@jitendra9nov asked a similar question in #108. [Here was my response](https://github.com/react-querybuilder/react-querybuilder/issues/108#issuecomment-1182425651) which linked to [this CodeSandbox](https://codesandbox.io/s/w4m2ox?file=/src/App.tsx).

**Comment by Sax-Yusuph** [comment]
thanks. finally went ahead with Part 1.

**Comment by jakeboone02** [comment]
I have some new thoughts on this topic. Please see https://github.com/react-querybuilder/react-querybuilder/issues/919#issuecomment-3146746032.

**Comment by jakeboone02** [comment]
OK I've finally produced something of substance regarding this request.

What I came up with was a companion package `@react-querybuilder/rules-engine` which builds on `react-querybuilder` with a `RulesEngineBuilder` component. It also includes the method `formatRulesEngine`&mdash;an export function like `formatQuery`&mdash;currently supporting [`json-rules-engine`](https://github.com/CacheControl/json-rules-engine).

I'm going to leave this package purposely undocumented (or maybe _lightly_ documented) for now to allow for feedback-directed changes and improvements without having to rewrite docs.

You can install the package from npm:

```sh
npm i @react-querybuilder/rules-engine
# OR yarn add / pnpm add / bun add
```

I've also set up a sandbox here: https://stackblitz.com/edit/github-hahtpo1r?file=src%2FApp.tsx

The data structure ended up being more of a wrapper around RQB's standard query object rather than an augmentation of it. Each step in an if-else chain identifies an `antecedent` (the "if" or "else if" condition) and an optional `consequent` (the result or action to be taken when a condition is true).

A rules engine object might look like this: 

```ts
const re: RulesEngine = {
  // Series of conditions ("if, else-if, else-if, ...")
  conditions: [
    // Condition 1 ("if...")
    {
      // Antecedents are query builder objects (`RuleGroupType`/`RuleGroupTypeIC`)
      antecedent: {
        combinator: "and",
        rules: [{ field: "age", operator: ">=", value: 18 }],
      },

      // Consequents ("then...") are the result of a successful/passing antecedent
      // They can be any object with a `type` property
      consequent: {
        type: "send_email",
        params: { to: "user@example.com", subject: "Welcome!", body: "Thanks for signing up!" },
      },

      // A condition can have sub-conditions
      conditions: [
        {
          antecedent: {
            combinator: "and",
            rules: [{ field: "age", operator: "=", value: 18 }],
          },
          consequent: {
            type: "send_email",
            params: { to: "user@example.com", subject: "Happy Birthday!", body: "🎂" },
          },
        },
      ],
    },

    // Condition 2 ("else if...")
    {
      antecedent: { combinator: "and", rules: [{ field: "age", operator: "<", value: 18 }] },

      // Consequent 2 ("then...")
      consequent: {
        type: "send_email",
        params: { to: "user@example.com", subject: "Sorry!", body: "Must be 18 to sign up." },
      },
    },
  ],

  // Optional "else" block
  defaultConsequent: { id: "3", type: "log_event" },
};
```

The prop types for the `RulesEngineBuilder` component are here:

https://github.com/react-querybuilder/react-querybuilder/blob/639867e705f4d23a85d06d5d15af540946d580e6/packages/rules-engine/src/types/props.ts#L129-L167

Please use #919 to ask any questions or add any feedback you may have.
