### ISSUE TITLE
Custom export/import formatters/transformers

### ISSUE THREAD

**Issue by unrealsolver** [react-querybuilder/react-querybuilder#400]
There is currently impossible to extend base functions to support my own custom export/import formats.
I need a JQL-like import/export formatting and the only option is to write it from scratch, because I can not extend existing formatters.

**Comment by jakeboone02** [comment]
Hi, @unrealsolver. Yeah, each language is different so it's difficult to provide general-purpose, extensible import and export methods.

For exporting, `formatQuery` has some configurations and hooks that allow you to customize the output of each rule, but the basic structure of each export format is going to be fixed and unique. For importing, each language uses its own bespoke parser.

Can you give me an example of the API you'd like to see? What would you be expecting from a DX perspective? Maybe we can provide something better if we have a goal defined.

As for JQL, I've never really thought about adding support for it since its use is limited to Jira (is that a correct statement?) but we use Jira at my workplace so I'm familiar enough with JQL to have a go at it. Stay tuned.

**Comment by unrealsolver** [comment]
Hello, @jakeboone02 , thanks for answering my question.
It looks, that I want to have a 'custom' language, which is similar to CEL, so I just decided to copy some files directly and modify them.
On the other hand, I have a problem of formatting the query to ElasticSearch format. However, formatting is much more trivial problem than parsing, so there are should be no issue. Probably, I could make a PR to this repo, because it could be used by other people around as well.

**Comment by jakeboone02** [comment]
PR's are welcome! Let me know if you need any help. Want to go ahead and close this issue?

**Comment by jakeboone02** [comment]
FYI, I added a task to import JQL on #316. I'm curious if the SQL importer could handle most JQL queries, for export as well as import.

**Comment by unrealsolver** [comment]
Maybe, for the simplest queries, SQL formatter might work for JQL, but they are quiet different. JQL is more like CEL. Anyway, since I need a little bit non-vanilla CEL/SQL language, I will have to use some custom logic for that. I think the issue could be closed now.
