### ISSUE TITLE
I need to know the other input's value at the same level

### ISSUE THREAD

**Issue by turhansel** [react-querybuilder/react-querybuilder#436]
Hey guys, I created a query builder. I need to know the other input's value at the same level, but I couldn't find a function for it. For example; I have city and district fields at the same level. I will send a request to the backend and create the district field according to the selected city. Is there any way to do this?

**Comment by jakeboone02** [comment]
~~The easiest way to do this is probably to pass the `query` down through the `context` prop to your custom value editor (something like `<QueryBuilder context={{ query }} />`).~~

_Edit 2025-03-27: For v7+, use the [`useQueryBuilderQuery`](https://react-querybuilder.js.org/docs/utils/hooks#usequerybuilderquery) hook instead of passing the `query` down through `context`._

Your value editor can then use `findPath` and `getParentPath` to get the sibling rules, find the "district" rule, and use that in the "city" rule.

~~Example CodeSandbox here: https://codesandbox.io/s/cool-lehmann-hm7no8?file=/src/App.tsx~~

_Updated sandbox 2025-03-27: https://codesandbox.io/p/devbox/4vyz24?file=%2Fsrc%2FApp.tsx_

Relevant code:

```tsx
// custom value editor
const VE = (props: ValueEditorProps) => {
  const query = useQueryBuilderQuery(props);
  const district = findPath(
    getParentPath(props.path),
    query // Prior to v7, this line would be `props.context.query` (see note above)
  ).rules.find((r: RuleType) => r.field === 'district').value;

  if (props.field === 'city') {
    return (
      <>
        <ValueEditor {...props} />
        {district}
      </>
    );
  }
  return <ValueEditor {...props} />;
};
```

**Comment by turhansel** [comment]
Thank you so much, Jake, you saved my day. I am thankful to you 🎉
