### ISSUE TITLE
Using the crypto module causes an error when building via esbuild with target not Node 

### ISSUE THREAD

**Issue by Alqanar** [react-querybuilder/react-querybuilder#442]
After upgrading the `react-querybuilder` package from version 5.2.0 to version 5.3.3, esbuild began to drop with the error "Could not resolve "crypto""

<img width="1060" alt="Screenshot 2023-01-06 at 16 00 41" src="https://user-images.githubusercontent.com/41822696/211008971-179584f3-09f4-4edf-ab5c-5ff7cf0a6c73.png">

**Comment by jakeboone02** [comment]
Ugh. I think I may have to abandon my attempt to use the `crypto` package for generating `id`s.

I'll put out a patch later today that reverts to using `Math.random` or something similar.

Apologies for the inconvenience!

**Comment by jakeboone02** [comment]
@Alqanar Can you try [v5.4.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v5.4.0)? It should fix the issue with `require('crypto')`.

**Comment by Alqanar** [comment]
@jakeboone02  Great! Thanks for the quick response and the fix. I will definitely try it on Monday.

**Comment by Alqanar** [comment]
@jakeboone02 For id generation, I can advise you to consider this package. It seems to solve the problem with crypto https://github.com/ai/nanoid

**Comment by jakeboone02** [comment]
It’s funny you mention that package. The short story is that we did use it a few years ago but removed it in favor of `` () => `${Math.random()}` `` because of IE11 and `crypto`.

I did some research and got the longer story. Sorry for the length, but I've got a question for you at the end...

`nanoid` originally replaced `uuid` in #102, resolving #97 which was a request to be able to provide a custom `id` generator. I rejected the original request (then implemented it in [v5.4.0](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v5.4.0) anyway with the [`idGenerator` prop](https://react-querybuilder.js.org/docs/api/querybuilder#idgenerator)!) but merged #102 to satisfy the user's requirement of shorter `id`s.

#143 highlighted the fact that IE11 used `window.msCrypto` instead of `window.crypto`, so I merged #144 which added full IE11 support, as long as the user [implemented a workaround for `msCrypto`](https://github.com/react-querybuilder/react-querybuilder/tree/4f383d7f3d5dad953849ff1bfa22902a36ba4316#ie11-support).

Later, we got around to addressing #128 which documented an issue with server rendering using Next.js. After some trial and error with `short-uuid`, I gave up on using an `id` package at all and merged #175 which replaced `nanoid` with `` () => `${Math.random()}` ``.

Mostly I just wanted to remove the requirement for the IE11 hack. IE11 isn't supported anymore, so that's no longer an issue and we can use `crypto` safely in the browser.

However, the main problem I encountered with using `crypto` was that it was available on the `window`/`globalThis` object in the browser, but not available by default on the server (see my [SO question](https://stackoverflow.com/q/75022492/765987)). It looks like `nanoid` solves this problem by using the `"exports"` field in their package.json to serve different files depending on the environment. (I've been thinking about migrating RQB to that structure as well: see #396.)

My question is this: the [first line of `nanoid`'s server code](https://github.com/ai/nanoid/blob/main/index.js#L1) is

```
import { randomFillSync } from 'crypto'
```

so wouldn't you run into the same `Could not resolve "crypto"` problem as you did with RQB v5.3.3's `require('crypto')` line, since you're not targeting NodeJS?

**Comment by Alqanar** [comment]
Hi. I tried to install and use the `nanoid` package because I saw it using `crypto`. But using nanoid does not cause an error. Apparently this package somehow solves this error

**Comment by Alqanar** [comment]
Hi Jake! I tried installing version 5.4.0 in the project, the error esbuild does not repeat. Thanks again for the quick response!

**Comment by jakeboone02** [comment]
That's great news! Glad I could help.

I'm really curious how the `nanoid` package imports from `'crypto'` but still works with your non-NodeJS esbuild target. Do you have a sample repo or config you could share that shows it working?
