### ISSUE TITLE
How to add tree view with MUI package

### ISSUE THREAD

**Issue by GabriFila** [react-querybuilder/react-querybuilder#453]
Hello!
Love this package, very useful.

I cannot get to display tree view lines (the `show branches` toggle) using the MUI package. 
- I loked for a prop, but can't find it in the typings.
- Also looking at the demo nothing seems to change. 
- I tried to add `controlClassnames={{ queryBuilder: ['queryBuilder-branches'] }}` but it doesn't work.

Can you help me plase?
Thank you

**Comment by jakeboone02** [comment]
That's weird, the demo is working for me (see below).

I just realized the `App.tsx` code shown below the demo doesn't demonstrate the "Show branches" option at all, so I can fix that. But anyway your third bullet looks like correct code (although you _might_ try using a plain string instead of an array...and let me know if that works because the array _should_ also work).

Can you set up a CodeSandbox or StackBlitz or something to demonstrate the issue you're seeing? MUI template is here: https://github.com/react-querybuilder/react-querybuilder/tree/main/examples/material

![image](https://user-images.githubusercontent.com/366438/214073227-c5301e2e-53b6-4e9b-adf4-73df105f9253.png)

**Comment by GabriFila** [comment]
Sorry my bad, I upgraded only the `material` package to the latest version, not the `core` one.

A side note, I tried running the [CodeSandbox](https://codesandbox.io/s/github/react-querybuilder/react-querybuilder/tree/main/examples/material) example but it throws a React Error. Stackblitz worked fine.

The error is the following: `(0 , _react.createContext) is not a function`, probably better to check directly on the sandbox

**Comment by jakeboone02** [comment]
> I tried running the [CodeSandbox](https://codesandbox.io/s/github/react-querybuilder/react-querybuilder/tree/main/examples/material) example but it throws a React Error. Stackblitz worked fine.
> 
> The error is the following: `(0 , _react.createContext) is not a function`, probably better to check directly on the sandbox

Yeah I've had trouble getting the packages to work correctly in CS. Sometimes I refresh it or fork it and it works. Anyway thanks for the report!
