### ISSUE TITLE
Validate(or test) jsonlogic with a user input,

### ISSUE THREAD

**Issue by Akhil017** [react-querybuilder/react-querybuilder#507]
Hey, I was wondering is there any way to validate the jsonlogic with a given input value?

**Comment by jakeboone02** [comment]
I'm sorry I don't understand what you mean. Can you elaborate?

**Comment by Akhil017** [comment]
Sure, the use case is more like a form builder where the admin will create a form first. While adding fields to the form, I am using React Query Builder to create validation logic (in jsonlogic) for an input field. For example, if the input field is "purchase date," then you i will create a jsonlogic where it says it should be between date A and date B, and this jsonlogic is saved to the database.

Now, when the user actually enters the value, you will fetch the jsonlogic from the database. However, now I need to validate or test the user's input against this jsonlogic. This can be done using the json-logic-js package, which provides a method called "apply."

I was wondering if there is a similar method to validate that jsonlogic against the user input.

**Comment by jakeboone02** [comment]
I think I understand what your use case is, but I'm still not sure exactly what the question is because the way I'm reading it, it seems like you answered it yourself.

Let me see if I have this straight: An admin creates a form and uses RQB to design a validation function (which you export and store as JsonLogic) for each field in the form. Then when an instance of the form is displayed to an end user, JsonLogic's `apply` method is used to validate their input as they fill in the form.

If that's correct, then I'm not sure what else needs to be validated. Apologies for my confusion.

**Comment by Akhil017** [comment]
Sorry for the confusion. My question was, is there any method in RQB to validate user input? I don't want to use an extra package (json-logic-js) if there is already a method in RQB.

**Comment by jakeboone02** [comment]
Oh I see what you mean now. No, there aren't any functions provided by RQB that validate input. There is a `defaultValidator` function but it only validates groups, not rules. The documentation for all the validation-related features of RQB is here: https://react-querybuilder.js.org/docs/utils/validation.

**Comment by Akhil017** [comment]
Hmm, it seems like I need to use the jsonlogic library itself. Thanks for the replies. :)
