### ISSUE TITLE
is this possible to show the "not switch" in every rule added ?

### ISSUE THREAD

**Issue by AzizBoughattas** [react-querybuilder/react-querybuilder#527]
it possible to show the "not toggle" in every rule added just before the operators selector ? (i find it more logic than being on top with the combinators) , cause i want to control if i want to use it or not in every rule added

**Comment by jakeboone02** [comment]
The reason it's at the group level is that it corresponds to the group-negating syntax in the export formats, like the `NOT` keyword in SQL.

Would you want to have a `not: boolean` property on each rule object? If so, you'd either need to create a custom `Rule` component or add the "not" switch to a custom `operatorSelector` component. The latter could render both the new component and the standard operator selector.

But I'm not sure what your use case is since each operator has an inverted counterpart already, e.g. `"="`/`"!="` and `"contains"`/`"doesNotContain"`.

**Comment by AzizBoughattas** [comment]
Hello again @jakeboone02  , thanks for responding ,
yes i want to have a not boolean on each rule and yes it was the operatorSelector that i needed but im having a problem when i toggle the "not switch" button in a specific rule it changes in all the rules

**Comment by jakeboone02** [comment]
Set up a sandbox with what you have so far and I'll take a look. Starter templates are [here](https://github.com/react-querybuilder/react-querybuilder/tree/main/examples).

**Comment by AzizBoughattas** [comment]
@jakeboone02 [sandbox](https://codesandbox.io/p/sandbox/dank-lake-32gytm?file=%2Fsrc%2FApp.jsx%3A59%2C63)
try the contains,startsWith,beginsWith operators ... what i want is each rule can control her own not value

**Comment by jakeboone02** [comment]
@AzizBoughattas Try this: https://codesandbox.io/p/sandbox/boring-field-hfjc4y?file=%2Fsrc%2FApp.jsx%3A1%2C1

**Comment by AzizBoughattas** [comment]
@jakeboone02 again, thanks a lot
