### ISSUE TITLE
Can I add a custom button to the entire query selector component?

### ISSUE THREAD

**Issue by camposfyi** [react-querybuilder/react-querybuilder#533]
I would like to add a custom button next to the lock button for the entire query selector (where the yellow X is).
Is this possible? I see options to customize individual components within each rule, but not the entire component.

<img width="484" alt="image" src="https://github.com/react-querybuilder/react-querybuilder/assets/5265784/bbf5343d-3e48-443d-85df-c47f68dffdac">

**Comment by jakeboone02** [comment]
There are a couple of ways to go about this. My first suggestion would be to render the default lock group button _and_ your custom button as part of the `lockGroupAction` control. Something like this:

```tsx
import { ActionElement, ActionWithRulesAndAddersProps } from 'react-querybuilder';

export const CustomLockGroup = (props: ActionWithRulesAndAddersProps) => {
  return (
    <>
      <ActionElement {...props} />
      <button onClick={() => alert('Hello, World!')}>HW</button>
    </>
  );
};
```

Which looks like this:

![image](https://github.com/react-querybuilder/react-querybuilder/assets/366438/0e802016-f233-42cb-a680-bcb5ace6bba0)

Working example here: https://codesandbox.io/p/sandbox/happy-shirley-4rfl5y?file=%2Fsrc%2FApp.tsx%3A6%2C26

The other option is to custom render the entire `RuleGroup` component. That's not as complicated as it may sound because all the default logic and even the rendering of sub-components is encapsulated in hooks or easy-to-render wrapper components. The basic idea is to copy the [`RuleGroup` source code](https://github.com/react-querybuilder/react-querybuilder/blob/b25797530e5e199ccf05fc91002db3bc77a4481e/packages/react-querybuilder/src/components/RuleGroup.tsx#L8-L42) (only ~25 lines), modify the JSX as you see fit, and apply that to the `ruleGroup` property of the `controlElements` prop. Note that `RuleGroupHeaderComponents` and `RuleGroupBodyComponents` return React Fragments, meaning you can do something like this:

```tsx
export const CustomRuleGroup = (props: RuleGroupProps) => {
  const rg = { ...props, ...useRuleGroup(props) };

  // ...other stuff...

  return (
    <div ref={rg.previewRef} className={rg.outerClassName}>
      <div ref={rg.dropRef} className={rg.classNames.header}>
        <RuleGroupHeaderComponents {...subComponentProps} />
        {/* SEE NEXT LINE: */}
        <button onClick={() => alert('Hello, World!')}>HW</button>
      </div>
      <div className={rg.classNames.body}>
        <RuleGroupBodyComponents {...subComponentProps} />
      </div>
    </div>
  );
};
```

The `<button>` below the comment will be a sibling element to all the other group header sub-components, just like with the previous method.

Hope that at least gives you some ideas!

**Comment by camposfyi** [comment]
Thank you. The first option worked great for what I needed.
