### ISSUE TITLE
Changing from a multiselect value editor to a select value editor does not clear values

### ISSUE THREAD

**Issue by nesl247** [react-querybuilder/react-querybuilder#551]
If you have a field with an operator that uses multiselect (for example `in`) and then change to an operator that does not allow multiselect, but uses select (for example, `=`), then the values are not being updated to only contain 1 value.

**Expected:**

Before:

`field1` `in` `['value1', 'value2']`

After:

`field1` `=` `'value1'`

**Actual:**

Before:

`field1` `in` `['value1', 'value2']`

After:

`field1` `=` `['value1', 'value2']`

**Comment by jakeboone02** [comment]
Yeah this makes sense. I'm only hesitant to implement it because I feel like there are some edge cases I'd miss where this wouldn't apply and might cause issues. That said, tell me if this logic sounds right:

- If the `useValueEditor` hook is executed (as when the default `ValueEditor` component is rendered),
- and the `value` is an array (`Array.isArray(value) === true`),
- and the `operator` is anything _other than_ `'between'`, `'notBetween'`, `'in'`, or `'notIn'`,
- then update the `value` to `value[0]`.

**Comment by nesl247** [comment]
> Yeah this makes sense. I'm only hesitant to implement it because I feel like there are some edge cases I'd miss where this wouldn't apply and might cause issues. That said, tell me if this logic sounds right:
> 
> * If the `useValueEditor` hook is executed (as when the default `ValueEditor` component is rendered),
> * and the `value` is an array (`Array.isArray(value) === true`),
> * and the `operator` is anything _other than_ `'between'`, `'notBetween'`, `'in'`, or `'notIn'`,
> * then update the `value` to `value[0]`.

That makes sense to me.

**Comment by jakeboone02** [comment]
So `useValueEditor` already does something similar, but only when `inputType === 'number'`.  This is the current `useEffect` call:

https://github.com/react-querybuilder/react-querybuilder/blob/a08a980bfeb03e2c4c64ad7e28d92bd8ad7640af/packages/react-querybuilder/src/hooks/useValueEditor.ts#L44-L53

I would propose this:

```ts
  useEffect(() => {
    if (skipHook) return;
    if (
      !['between', 'notBetween', 'in', 'notIn'].includes(operator) &&
      (Array.isArray(value) ||
        (inputType === 'number' && typeof value === 'string' && value.includes(',')))
    ) {
      handleOnChange(toArray(value)[0] ?? '');
    }
  }, [handleOnChange, inputType, operator, skipHook, value]);
```

This would reset the `value` to `value[0]` for _all_ `inputType`s when `value` is an array, not just for `'number'`, and `'number'`-types would still reset to `value.split(',')[0]` when `typeof value === 'string'`. That sound right?

(Also, just for reference: you can avoid these automatic updates while still benefiting from calling `useValueEditor` from a custom `ValueEditor` by including `{ skipHook: true }` in the parameter object.)

**Comment by jakeboone02** [comment]
@nesl247 I've made this change in #537. I don't know exactly when it will be released because I'm also working on an overhaul of the types to improve inference. TypeScript for library maintainers can be...a lot. Anyway, maybe I'll do another v6.6.0 alpha release soon. It's getting bigger so it might actually end up being v7.0.0.

**Comment by nesl247** [comment]
> @nesl247 I've made this change in #537. I don't know exactly when it will be released because I'm also working on an overhaul of the types to improve inference. TypeScript for library maintainers can be...a lot. Anyway, maybe I'll do another v6.6.0 alpha release soon. It's getting bigger so it might actually end up being v7.0.0.

Thanks! It’s not a rush since we fixed it ourselves locally. We just reported it because our fix was kind of hacky and we didn’t want to maintain it forever.
