### ISSUE TITLE
Accept style-library-specific props in compatibility package value editors

### ISSUE THREAD

**Issue by jsungg** [react-querybuilder/react-querybuilder#555]
Hi, so currently all other chakra controlElements from `@react-querybuilder/chakra` are able to pass in chakra style props for styling 

Example: 

```
const baseChakraControlElements: Partial<Controls> = {
    ...chakraControlElements,
    fieldSelector: (props: FieldSelectorProps) => (
      <ChakraValueSelector {...props} size={size} />
    ),
    combinatorSelector: (props: CombinatorSelectorProps) => (
      <ChakraValueSelector {...props} size={size} />
    ),
    operatorSelector: (props: OperatorSelectorProps) => (
      <ChakraValueSelector {...props} size={size} />
    ),
    addRuleAction: (props: ActionWithRulesAndAddersProps) => (
      <ChakraActionElement {...props} size={size} px={4}/>
    ),
    addGroupAction: (props: ActionWithRulesAndAddersProps) => (
      <ChakraActionElement {...props} size={size} px={4}/>
    ),
    removeGroupAction: (props: ActionWithRulesProps) => (
      <ChakraActionElement {...props} size={size} />
    ),
    removeRuleAction: (props: ActionWithRulesProps) => (
      <ChakraActionElement {...props} size={size} />
    ),
  };
```

However for the `<ChakraValueEditor />` component, it does not have access to the ChakraUI style props that the other control elements have access to, so there is no way to finely control the style for the input inside the `<ChakraValueEditor/>` component when passing it as an overriden control element for  `<QueryBuilder />`

Example: 

```
<ChakraValueEditor {...props} size={size} /> // this will not work, as size does not exist as a prop
```

**Comment by jakeboone02** [comment]
Hi @jsungg! Thanks for bringing this up. Actually none of the value editors in any of the compatibility packages accept extra props specific to their respective style library like the value selectors, buttons, and other components do.

The reason is that value editors, `ChakraValueEditor` in your case, can render one of several different (Chakra) components depending on the props, and I couldn't union all the props types for all the possible rendered components. When I originally created them, I didn't think enough about how to get them to accept custom props for several different components in one props object, but I think I know how to do it now, so I'll try to address this in v7.0.0 (no ETA on that yet).
