### ISSUE TITLE
If I want to implement left join or order, which direction can I start with? Is there a demo?

### ISSUE THREAD

**Issue by Hideer** [react-querybuilder/react-querybuilder#603]
As title

**Comment by jakeboone02** [comment]
If you're talking about SQL clauses, RQB doesn't manage anything other than the `WHERE` clause. I guess you could throw `HAVING` in there since the syntax is similar to `WHERE`. But `SELECT`, `FROM`/`JOIN`, `ORDER BY`, `GROUP BY`, etc., would require a separate component.

An exception might be Oracle's `(+)` syntax for defining outer joins in the `WHERE` clause, but I think all the other major RDBMS's either don't support or don't recommend that style.
