### ISSUE TITLE
parseCEL method is not working for does not contain, does not begin with, does not end with, not in

### ISSUE THREAD

**Issue by harishviswa-10** [react-querybuilder/react-querybuilder#682]
### Description

I have converted the RuleGroupType to CEL Expression using formatQuery(query, "cel") method, it is working fine. When i try to convert the CEL Expression back to RuleGroupType using the parseCEL method, the RuleGroupType is not as same as the initial RuleGroupType. Operators which are not working when converting CEL Expression to RuleGroup Type: does not contain, does not begin with, does not end with, not in
1. This is the query generated when converting to RuleGroup Type to CEL Expression :  field == "marks" && (!value.startsWith("68")).
2. When converting it back to Rule Group type using parseCEL getting this value:  field == "marks"

### Reproduction

Construct any query which consists of !(not) in front of it like this !value.startsWith("68") when converting to CEL Expression. You can do it  by selecting any of these operators: does not contain, does not begin with, does not end with, not in. 
Then try to convert the same CEL expression to RuleGroupType, you can find only the expression which doesn't include these operators

**Comment by noxify** [comment]
I can reproduce the behavior with your query.

~~The rootcause seems the position of the `!`.
In your query, it's inside the brackets.~~

Added some STRs, because what i assumed is wrong.

If you create the same query via the [demo ui](https://react-querybuilder.js.org/demo), you get the following query.

```
firstName == "firstname" && !(lastName.startsWith("68"))
```
<img width="1046" alt="image" src="https://github.com/react-querybuilder/react-querybuilder/assets/521777/b6610c15-9413-4ef5-9d96-c397cf495c17">


If you import the generated CEL query, you get the following result:

<img width="754" alt="image" src="https://github.com/react-querybuilder/react-querybuilder/assets/521777/3a0d70c6-12aa-4d67-b744-9e193741f28d">

If you import then the generated query:

```
firstName == "firstname" && (!lastName.startsWith("68"))
```

it results in your error:
<img width="732" alt="image" src="https://github.com/react-querybuilder/react-querybuilder/assets/521777/80bc2774-d363-44ed-98e3-74c39bfba90d">

The error occurs also if you do not use the brackets around the second part:

```
firstName == "firstname" && !lastName.startsWith("68")
```

**Comment by jakeboone02** [comment]
Thanks for the investigation @noxify! This definitely seems like a fixable bug. Exported queries should be importable as is.

I'll take a stab at it soon...unless someone else wants to have a go.

**Comment by jakeboone02** [comment]
I just got around to looking at this over the weekend. Funny enough, I had put a `// TODO:` comment to fix this in the test file a long time ago:

https://github.com/react-querybuilder/react-querybuilder/blob/221085b07f16926e9436968f26c31fd50276201c/packages/react-querybuilder/src/utils/parseCEL/parseCEL.test.ts#L134-L135

Anyway, #689 should fix the issue. You can try out the new `parseCEL` behavior in the [preview website demo](https://deploy-preview-689--react-querybuilder.netlify.app/demo) or a [sandbox with the new build](https://codesandbox.io/s/react-query-builder-basic-typescript-template-mdpzqx).
