### ISSUE TITLE
`uniqOptGroups` issue / question

### ISSUE THREAD

**Issue by stasgavrylov** [react-querybuilder/react-querybuilder#782]
### React Query Builder version

7.4.0

### Platform

Mac OS

### Description

First of all, I'd like to thank authors and maintainers for making such a useful and configurable tool.

I am experiencing an issue caused by the logic inside `uniqOptGroups`: an array of fields is passed to `QueryBuilder` and 2 of those fields are lists with identical sets of options. Because if options deduplication logic inside `uniqOptGroups`, the normalized `fields` array used for rendering value editor component has an empty options array for the second field, since its options do not pass this check:

```ts
 const optionsForThisGroup: WithUnknownIndex<ToFullOption<T>>[] = [];
      el.options.forEach(opt => {
        if (!names.has((opt.value ?? opt.name) as K)) {
          names.add((opt.value ?? opt.name) as K);
          optionsForThisGroup.push(toFullOption(opt) as WithUnknownIndex<ToFullOption<T>>);
        }
      });
      newArray.push({ ...el, options: optionsForThisGroup });
```

I wasn't able to find the code to use deduplicated options in other fields which had those, so now I have an empty list of values instead of what comes from server config.
I don't know if it is relevant, but I am rendering a custom `ValueEditor` component, but I've looked through all properties of its `props.field` argument, and the original array of options is nowhere to be seen.

Am I missing something? How should deduplicated options be provided to all fields which should have those?

Thanks in advance.

### Reproduction

I can provide a reproducible example, but I hope that the case is clear from the description.

Here's a screenshot of what I'm experiencing:
- 2 objects on top are the fields with identical options
- the object at the bottom if the `field` property when the second field is selected. you can see that the `options` array is empty.
- 
<img width="600" alt="image" src="https://github.com/user-attachments/assets/91950512-4231-4e33-9fff-ea94b785efb9">

### Expected behavior

Field's options are kept in place.

**Comment by jakeboone02** [comment]
> First of all, I'd like to thank authors and maintainers for making such a useful and configurable tool.

Thanks for the kind words!

> [...] I am rendering a custom `ValueEditor` component, but I've looked through all properties of its `props.field` argument

- `ValueEditorProps` (and every other component prop interface, for that matter) includes the full list of fields in the `schema.fields` property, not at the top level.
- `field` should be a `string`--not an object--matching the identifier (the `name` and/or `value` property) of an element of the `fields` prop.
  - The fact that `field` is an object in your screenshot of the value editor props leads me to suspect you're implementing a custom field selector that calls `props.handleOnChange` with the full object of the selected field rather than its identifier string.
  - Even though `field` is a `string`, the full field object is still available as `fieldData`.

Based on the values in those `options` arrays, they look more like lists of operators. Assuming that's what they really are...

What's happening now is that RQB sees the `options` property in the top-level elements and assumes the list is of type `OptionGroup[]` instead of `Option[]` ([more info here](https://react-querybuilder.js.org/docs/tips/option-lists)). This causes it to remove the "duplicates" because those are the selectable field values. Having two with the same identifier doesn't make sense.

What _should_ be the field objects--the top-level array elements with values `"contactCenterHours"` and `"partnerBusinessHours"`--are rendered as non-selectable `<optgroup>`s.

I think if you rename the `options` property of each field object to `operators`, this should resolve the issue.

See also: [Managing operators](https://react-querybuilder.js.org/docs/tips/managing-operators).

**Comment by stasgavrylov** [comment]
Thank you for such a detailed response. I'll keep digging.

I've also noticed that `field` should've been a string, based on the typings, but for some reason I get the whole object in there, so I've had to build some workarounds. Maybe I've missed something in the documentation, so I'll definitely have to recheck if I'm cooking it correctly :)
