### ISSUE TITLE
Instructions for disconnecting react-querybuilder from Redux devtools

### ISSUE THREAD

**Issue by Amy-B-Tradition** [react-querybuilder/react-querybuilder#809]
**Documentation: provide instructions to disconnect react-querybuilder from Redux devtools**

It's not clear how to prevent your Redux state from using memory and cluttering up Redux dev tools.

**We don't need to see and couldn't do anything with your Redux state if we looked at it**

We're using Redux-observables, and they already use a lot of memory in devtools. Being able to ditch unnecessary state would be helpful. Also, your Redux state bubbles to the top of the list. It's not even obvious that's a select list (not your fault), but since we only have one Redux store that we made in our app, it's not ideal that we have to use that unintuitive dropdown to select ours just because yours is there.

**Comment by jakeboone02** [comment]
Honestly, I didn't even realize RQB showed up in Redux DevTools. RQB uses a custom React context for its Redux store, and I just assumed it was invisible to the DevTools without ever thinking to check!

The issue you raise is a little tricky because the store gets configured as soon as the module loads, and there aren't really any parameters to pass in an `import` statement. Here are my thoughts so far:

### Short-term mitigation (?)

The Redux DevTools drop down list sorts the stores in the order they were registered. If you're statically `import`ing `QueryBuilder`, the RQB store gets registered first and therefore comes first in the drop down.

You can force RQB to register after your own store (and show up last in the drop down) by dynamically `import`ing it:

```tsx
// App.tsx
import { QueryBuilder } from "react-querybuilder";
export default function App() {
  return <QueryBuilder />;
}

// index.tsx
import { store } from "./store";
const App = React.lazy(() => import("./App"));
createRoot(document.querySelector("#app")!).render(
  <Provider store={store}>
    <React.Suspense fallback={<div>Loading...</div>}>
      <App />
    </React.Suspense>
  </Provider>
);
```

If that's not feasible (or worth the trouble) in your case, we'll have to make changes in RQB itself...

### Redux store name

The RQB Redux store doesn't declare a `name` in the `configureStore` `devTools` property. That would at least make it a little clearer which store you're looking at. I'll fix that in the next version.

### Hiding RQB from Redux DevTools

I'm sympathetic to the idea of hiding RQB from Redux DevTools altogether since, as you say, there's not much you can do with it and it can cause confusion. However, I'd like to leave the option open to include it. Since the store gets registered as soon is the module is loaded, the configuration has to be done in the import itself. I'm not exactly sure how to do that right now...maybe a separate component or a separate export path.

I think what I'd like to do is set the `devTools` property to `false` by default, then add a `/debug` export path that registers the store with `devTools: { name: 'React Query Builder' }`. So when you want to see the RQB store in the Redux DevTools, you'd do something like this:

```tsx
import { QueryBuilder } from "react-querybuilder/debug";
// ...or maybe this instead:
import { QueryBuilderDebug } from "react-querybuilder";
```

Thanks for bringing this to my attention!

**Comment by jakeboone02** [comment]
@Amy-B-Tradition I put up PR #814 that adds a `"react-querybuilder/debug"` export path that registers the RQB Redux store with Redux DevTools. Normal `"react-querybuilder"` imports will _not_ register the store.

You can test it out here: https://codesandbox.io/p/devbox/whk2k6?file=%2Fsrc%2FApp.tsx%3A2%2C1-8%2C1

Let me know what you think!

**Comment by Amy-B-Tradition** [comment]
I'd be ok if you just had a custom name so it was obvious what is going on. I spent a long time trying to figure out why I couldn't see our Redux state in dev tools. Unfortunately, with the holidays coming up and the time off that implies, I don't know when I'll be able to get to this.

**Comment by jakeboone02** [comment]
Thanks. Given that you're OK with just the custom name, I'm going to go ahead and move forward with the debug build (that includes the custom name) since it also lays the groundwork for some other enhancements I've been considering.
