### ISSUE TITLE
DoubleNegation doesn't seem to parse

### ISSUE THREAD

**Issue by janvandenberg** [react-querybuilder/react-querybuilder#819]
### React Query Builder version

8.0.0

### Platform

Mac OS

### Description

I'm encountering issues with double negation rules in JsonLogic with React QueryBuilder. While the codebase appears to have some support for this feature, I haven't successfully parsed any double negation rules yet. I've searched the documentation but found no specific guidance on this topic. Does anyone have experience implementing double negation rules in JsonLogic, or could point me to relevant documentation? Examples would be especially helpful."
```
{
      "and": [
        {
          "!!": 
            { "var": "myvariable" },
        }
      ]
    }
```

### Reproduction

```
    console.log("should work:", parseJsonLogic({
      "and": [
        {
          "!!": 
            { "var": "test" },

        }
      ]
    }));
```

### Expected behavior

Expected rules in the result object

**Comment by jakeboone02** [comment]
Would you expect the rule to be this:

```
{ field: "test", operator: "=", value: true }
```

...or this:

```
{ field: "test", operator: "!=", value: false }
```

**Comment by janvandenberg** [comment]
I would expect something like this:

```
const result = parseJsonLogic({
      "and": [{
          "!!": [{
                  "var": "test"
              },
              ""
          ]
      }]
});
      
console.log(result);
// Outputs: { "and": [ { field: "test", operator: "!!", value: false } ] }
      
const result2 = parseJsonLogic({
      "and": [{
          "!!": [{
                  "var": "test2"
              },
              "123"
          ]
      }]
});
console.log(result2);
// Outputs: { "and": [ { field: "test", operator: "!!", value: true } ] }
```

**Comment by jakeboone02** [comment]
You can handle operations however you want with the [`jsonLogicOperations` option](https://react-querybuilder.js.org/docs/utils/import#custom-operations).

**Comment by janvandenberg** [comment]
Ok. I missed that. Thanks @jakeboone02

**Comment by jakeboone02** [comment]
I should elaborate on my response, since I sort of implicitly rejected your suggestion.

Implementing the behavior you indicated would require support for a `"!!"` operator within `parseJsonLogic` of course, but also in `formatQuery` and probably the `ValueEditor` component. That operator coerces any value to a particular JavaScript data type, `boolean`. Since the end result is a "Boolean" value, it makes sense in all logical contexts, but the semantics are specific to the JavaScript language. I would rather avoid implementing something throughout the codebase that doesn't have a 1:1 analog in all our supported query languages.

I hope that makes sense. If you have other thoughts, feel free to share.

**Comment by janvandenberg** [comment]
I understand your point, considering the broader context. I wanted to use it to check for empty strings and arrays. But translating that the SQL, doesn't make sense. I believe not implementing this approach is the better choice. Thank you for your prompt responses.
