### ISSUE TITLE
Add field metadata to valueEditor

### ISSUE THREAD

**Issue by rubenbarros-byside** [react-querybuilder/react-querybuilder#91]
We have the necessity to change the valueEditor input, depending on some property of the selected field (to a datepicker, or two inputs, or a simple select vs simple input).

We need some kind of information to show the correct input, and as such, we added the metaData when adding a new rule, and when the field is changed, we populate the rule with the metaData of the selected field.

I made a fork from this at https://github.com/rubenbarros-byside/react-querybuilder

**Comment by jakeboone02** [comment]
Can you not base the valueEditor type on the field and operator alone?  If you need more information about the field, you could maintain that in a separate object or function and read that from your custom valueEditor component.

Something like this:
```jsx
const getFieldMetaData = field => {
  switch (field) {
    case 'FIELD1':
    case 'FIELD2':
      return 'datepicker';
    case 'FIELD3':
      return 'twoinputs';
    ...
  }
}

const ValueEditor = props => {
  const metaData = getFieldMetaData(props.field);
  switch (metaData) {
    case 'datepicker':
      return <DatePicker />;
    case 'twoinputs':
      return <div><input /><input /></div>
    ...
  }
}
```

Can you show an example of how this metaData prop would be used?

**Comment by vitorhsb** [comment]
In our scenario it is not possible to have a separate object or function to retrieve that metadata since our available fields are dynamic (with numeric ids) and retrieved by the backend. Even our operator values are based on dynamic info.

**Comment by jakeboone02** [comment]
Can you share an example of what the payload from the server looks like, and how you're translating that into the fields array?  I'm thinking if you have the field name and the operator, that should be enough to gather the metadata even if the field names are dynamic.  But if you could show some code maybe I'll understand better.

**Comment by zaphide** [comment]
I have a similar request (for example, I am also providing tooltips for all sorts of things in the custom valueEditor and custom operatorSelector I am using).

A possible simple (-ish?) solution might just be to pass (via props) the full Field object to the custom valueEditor and operatorSelector, then the Field object can be extended as needed.

For compatibility/simplicity it would probably be worth keeping the existing 'field' prop string and adding another, maybe a 'fieldData' prop?

**Comment by jakeboone02** [comment]
@zaphide, I'm still struggling to understand the necessity of a new prop when you can get what you need from an external object or function that's indexed by `field`.  See my example above.  Can you provide an example where this approach wouldn't work?

**Comment by zaphide** [comment]
Yeah I do agree it's not strictly 100% necessary and there are other ways it can be done but this (to me) feels more of a workaround of something that should be core functionality. 

Maybe consider something like a off-the-shelf grid component that supports fully customising the display of the data in each grid cell. Generally, such a component would allow passing the data structure through to the custom render function such that the full object is available for usage (in whatever form it may take) so that a custom render function does not have to call out/back to <something else> to get the full object (via an object key or similar).

I guess the part that is missing from your example is that when the source of the data for the fields is not hard coded, then we need considerably more application infrastructure than I feel should be necessary for providing (easily available) object data into essentially a render function.

I think for me it comes down to 'we have the object, and potentially a need for the whole object, so why not pass everything'. If I was writing this completely from scratch, I would much rather pass the full object to the child component rather than calling back/out to <something else> to get the data.

**Comment by jakeboone02** [comment]
OK, I think I understand what you're saying.

What if, instead of something specific to the `field` prop and `ValueEditor` components, we added a `context` prop that was passed to _every_ custom component?  The `context` prop could be anything (`any` in TypeScript), so you could store your field configuration in there or whatever else you'd need to render the elements.

We use `react-querybuilder` in conjunction with [`ag-grid`](https://github.com/ag-grid/ag-grid) at work, which is where I got the idea.

**Comment by zaphide** [comment]
Yeah I was also going to suggest something similar but didn't want to complicate things :)

We are using [office-ui-fabric-react](https://developer.microsoft.com/en-us/fabric/) and it generally has a similar `data` prop that can be used if needed.

Not sure if this would be worthwhile but could also use generics for the Typescript typings, so something like:
```
interface CommonCustomControlProps<T = any> {
   ...
   context?: T;
}

interface SelectorEditorCustomControlProps<T = any> extends CommonCustomControlProps<T> {...}

interface ValueEditorCustomControlProps<T = any> extends SelectorEditorCustomControlProps<T> {...}
```

which could then be type-enforced with something like:
```
export class MyCustomValueEditor extends React.PureComponent<ValueEditorCustomControlProps<string>> {
    constructor(props: ValueEditorCustomControlProps<string>) {
        super(props);

        const myString: string = props.context;
    }
}
```

Obviously instead of <string> the <type> for the context object could be whatever data structure is being used to store/manage fields.

I guess that then leaves what to do with individual operators, as passing custom data to a custom OperatorControl would be worthwhile too I think (both for the selected field, and for each individual operator, as constructed by the getOperators custom function). My use case here is again for tooltips, custom styling etc. per distinct operator.

But regardless, being able to pass via props additional data for fields would be awesome :)

**Comment by jakeboone02** [comment]
Feel like doing a PR for this?

**Comment by zaphide** [comment]
Sure, I'll put something together and PR it.

**Comment by jakeboone02** [comment]
@zaphide So... #105 wasn't exactly what I was thinking of, but it's close.  However, I actually took a look at the code today and I think I finally understand what you were saying in [this comment](https://github.com/sapientglobalmarkets/react-querybuilder/issues/91#issuecomment-531084209_) about a the `fieldData` prop.  That's a simpler solution and I think we should go with that.  I'll put a PR together so we can all have a look.

**Comment by zaphide** [comment]
Yeah definitly a simpler (and so generally better) option imo :) I was half way through the other implementation and was thinking it was a lot of work instead of just passing the field object :P

**Comment by jakeboone02** [comment]
@rubenbarros-byside and @vitorhsb - would you mind taking a look at #107 to see if that meets your requirements?  It adds a new `fieldData` prop to the ValueEditor and OperatorSelector components that includes the entire `field` object instead of just the `field` name.

**Comment by rubenbarros-byside** [comment]
@jakeboone02 , the PR seems to do what we need.

Thanks @zaphide .
